<?php
/**
 *
 * @var $this \Cubex\View\Layout
 *
 * This is your default layout file, variables in this file act as placeholders for named nested views
 *
 */
?>
<div class="container-narrow" id="wrapper">

  <div class="masthead">
    <ul class="nav nav-pills pull-right">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="/profile">Your Name</a></li>
      <li><a href="/logout">Logout</a></li>
    </ul>
    <h3 class="muted"><a href="/">Sidekick</a></h3>
  </div>
  <hr>

  <div class="row-fluid">
    <div class="span2">
      <?php echo $this->renderNest("sidebar"); ?>
    </div>
    <div class="span10">
      <?php echo $this->renderNest("tabnav"); ?>
      <?php echo $this->renderNest("content"); ?>
    </div>
  </div>

</div>
