<?php
/**
 * @author: oke.ugwu
 *        Application: Projects
 * @var $this \Sidekick\Applications\Projects\Views\ProjectsIndex
 */
?>
<h1>Projects</h1>
<a href="<?= $this->baseUri() . '/create-project'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create Project</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Name</th>
    <th>Description</th>
    <th>Last Update</th>
    <th></th>
  </tr>
  <?php foreach($this->getProjects() as $project): ?>
    <tr>
      <td>
        <a href=""><?= $project->name; ?></a>

        <div class="jump-links">
          <span>Jump to:</span>
          <ul>
            <?php if($project->repository() !== null): ?>
            <li>
              <a href="/repository/commits/<?= $project->repository()->id(); ?>">
                Repository
              </a>
            </li>
            <?php endif; ?>
            <li>
              <a href="/configurator/project/<?= $project->id(); ?>">
                Configurator
              </a>
            </li>
            <li>
              <a href="/fortify/<?= $project->id(); ?>">Fortify</a>
            </li>
            <li>
              <a href="/scripture/<?= $project->id(); ?>/README">Scripture</a>
            </li>
          </ul>
        </div>
      </td>
      <td><?= $project->description; ?></td>
      <td><?= date('d/M/Y', strtotime($project->updated_at)); ?></td>
      <td>
        <a href="<?= $this->baseUri() . '/edit/' . $project->id(); ?>"
           title="edit"><i class="icon-edit"></i></a>
        <a href="<?= $this->baseUri() . '/users/' . $project->id(); ?>"
           title="delete"><i class="icon-user"></i></a>
        <a href="<?= $this->baseUri() . '/delete/' . $project->id(); ?>"
           title="delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
