<?php
/**
 * @author: oke.ugwu
 *        Application: Projects
 * @var $this \Sidekick\Applications\Projects\Views\ProjectsIndex
 */
?>

<h1>Projects</h1>
<a href="<?php echo $this->baseUri() . '/create-project'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create Project</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Name</th>
    <th>Parent</th>
    <th>Description</th>
    <th>Created</th>
    <th>Last Update</th>
    <th></th>
  </tr>
  <?php foreach($this->getProjects() as $project): ?>
    <tr>
      <td><?php echo $project->name; ?></td>
      <td><?php echo $project->parent()->name; ?></td>
      <td><?php echo $project->description; ?></td>
      <td><?php echo date('d/M/Y', strtotime($project->created_at)); ?></td>
      <td><?php echo date('d/M/Y', strtotime($project->updated_at)); ?></td>
      <td>
        <a href="<?php echo $this->baseUri() . '/edit/' . $project->id(); ?>"
           title="edit"><i class="icon-edit"></i></a>
        <a href="<?php echo $this->baseUri() . '/delete/' . $project->id(); ?>"
           title="delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
