<?php
/**
 * @author: oke.ugwu
 *        Application: Projects
 * @var $this \Sidekick\Applications\Projects\Views\ProjectUsersList
 */
?>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Name</th>
    <th>Role</th>
    <th></th>
  </tr>
  <?php foreach($this->getUsers() as $user): ?>
    <tr>
      <td><a href=""><?= $user->user()->displayName; ?></a></td>
      <td><?= implode(', ', $user->roles); ?></td>
      <td>
        <a href="<?=
        $this->baseUri(
        ) . '/remove-user/' . $user->projectId . '/' . $user->userId; ?>"
           title="remove"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
