<?php
/**
 * Author: oke.ugwu
 * Date: 10/09/13 13:54
 *
 * @var $this \Sidekick\Applications\Diffuse\Views\Projects\Deployments\DeploymentDetailsView
 */

use Cubex\Helpers\Strings;
use Sidekick\Components\Diffuse\Helpers\DeploymentHelper;

?>
<a href="<?= Session::get('backUri') ?>" class="btn pull-right">Back</a>
<h1>Deployment #<?= $this->getDeployment()->id() ?></h1>

<p>Deployed to <?= Strings::titleize(
    $this->getDeployment()->platform()->name
  ) ?> on <strong><?=
    date(
      'd/m/Y @ H:i:A',
      strtotime($this->getDeployment()->createdAt)
    ) ?></strong> by <strong><?= $this->getUser() ?></strong></p>

<?php if($this->getDeployment()->comment != null): ?>
  <blockquote>
    <i>&quot;<?= $this->getDeployment()->comment ?>&quot;</i>
  </blockquote>
<?php endif; ?>

<?php foreach($this->getDeploymentStages() as $s): ?>
  <h2><?= DeploymentHelper::className($s->serviceClass) ?></h2>
  <table class="table table-bordered">
    <tr>
      <th>Time</th>
      <th>Host</th>
      <th>Passed</th>
      <th>Log</th>
    </tr>
    <?php foreach($this->getDeploymentDetail() as $d): ?>
      <?php if($d->deploymentStage()->serviceClass == $s->serviceClass): ?>
        <tr>
          <td><?= date('H:i:s', strtotime($d->createdAt)) ?></td>
          <td>
            <?= $d->host()->name ?>
            <span class="muted">(<?= $d->host()->ipv4 ?>)</span>
          </td>
          <td class="text-<?= $d->passed ? 'success' : 'error' ?>">
            <?= $d->passed ? 'Passed' : 'Failed' ?>
          </td>
          <td style="width:550px;"><?= $d->log ?></td>
        </tr>
      <?php endif; ?>
    <?php endforeach; ?>
  </table>
<?php endforeach; ?>
