<?php
/**
 * Author: oke.ugwu
 * Date: 28/06/13 10:14
 *
 * @var $this \Sidekick\Applications\Repository\Views\CommitFiles
 */
?>
<h1>Commit Files</h1>
<table class="table table-bordered">
  <tr>
    <th>File Name</th>
  </tr>
  <?php foreach($this->commitFiles as $file): ?>
    <tr>
      <td>
        <a href="/sourcecode/build/<?= $this->getRunId() ?>/<?= $file->filePath ?>;"
           target="_blank">
          <?= $file->filePath ?>
        </a>
        <span class="label"><?= $file->changeType ?></span>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
