<?php
/**
 * Created by JetBrains PhpStorm.
 * User: oke.ugwu
 * Date: 31/05/13
 * Time: 08:44
 * @var $this \Sidekick\Applications\Repository\Views\RepositoryIndex.
 */
?>
<h1>Repositories</h1>
<a href="<?php echo $this->baseUri() . '/add-repository'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Add Repository</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Name</th>
    <th>Type</th>
    <th>Description</th>
    <th>Created</th>
    <th>Last Update</th>
    <th></th>
  </tr>
  <?php foreach($this->getRepositories() as $repo): ?>
    <tr>
      <td><a href="<?php echo $this->baseUri().'/commits/'.$repo->id(); ?>">
          <?php echo $repo->name; ?></a>
      </td>
      <td><?php echo $repo->repositoryType; ?></td>
      <td><?php echo $repo->description; ?></td>
      <td><?php echo date('d/M/Y', strtotime($repo->createdAt)); ?></td>
      <td><?php echo date('d/M/Y', strtotime($repo->updatedAt)); ?></td>
      <td>
        <a href="<?php echo $this->baseUri() . '/edit/' . $repo->id(); ?>"
           title="edit"><i class="icon-edit"></i></a>
        <a href="<?php echo $this->baseUri() . '/delete/' . $repo->id(); ?>"
           title="delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
