<?php
/**
 * @var $this \Sidekick\Applications\Repository\Views\RepositoryIndex
 */
?>
<h1>Branches</h1>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Branch</th>
    <th>Name</th>
    <th>Commits</th>
    <th>Version</th>
    <th>Creation Date</th>
  </tr>
  <?php foreach($this->getBranches() as $branch): ?>
    <tr>
      <td>
          <?= $branch->branch; ?>
      </td>
      <td><?= $branch->name ?></td>
      <td>
        <a href="<?= $this->appBaseUri() . '/branch/' . $branch->id(); ?>/commits">
          <?= number_format($branch->commits()->count(), 0); ?>
        </a>
      </td>
      <td><?= $branch->majorVersion?:"x"; ?>.<?= $branch->minorVersion?:"x"; ?></td>
      <td><?= date('d/M/Y', strtotime($branch->createdAt)) ?></td>
    </tr>
  <?php endforeach; ?>
</table>

<a href="<?=$this->appBaseUri(); ?>/update">Update Repo</a>