<?php
/**
 * @author oke.ugwu
 * @var $this \Sidekick\Applications\Rosetta\Views\RosettaIndex
 */
?>

<div class="well pull-right">
  <form method="post" action="<?= $this->appBaseUri() ?>/search">
    <input class="input-xxlarge rosetta-search" type="text"
           placeholder="Start searching by typing the string of characters or the lookup ID."
           name="term"
      />
    <button class="btn btn-success search-btn">Search</button>
  </form>
</div>

<h1>Welcome to Rosetta</h1>
<p>Rosetta is the translations manager.</p>

<div class="clearfix"></div>

<div class="pull-right">
  <label for="">Select Language: </label>
  <select name="lang" id="" onchange="window.location.href='<?=
  $this->appBaseUri() ?>/'+$(this).val()">
    <option value="">--SELECT--</option>
    <?php foreach($this->getLanguageOptions() as $code => $language): ?>
      <option value="<?= $code ?>" <?=
      ($code == $this->getLanguage(
        )) ? 'selected="selected"' : '' ?>><?= $language ?></option>
    <?php endforeach; ?>
  </select>
</div>
<h2 class="pull-left-">Pending Translations Requiring Approval</h2>
<div class="clearfix"></div>
<button class="btn btn-success approve-selected" disabled="disabled">Approve
                                                                     Selected
</button>
<div style="margin-top:5px;"></div>
<table class="table table-bordered table-hover">
  <tr>
    <th><input type="checkbox" class="select-all"/></th>
    <?php foreach($this->getSelectedLanguages() as $language): ?>
      <th><?= $language ?></th>
    <?php endforeach; ?>
    <th>Approve</th>
  </tr>
  <?php foreach($this->getPendingTranslations() as $pending): ?>
    <tr>
      <td><input type="checkbox" class="text-selecter"
                 data-rowkey="<?= $pending->rowKey ?>"
                 data-lang="<?= $pending->lang ?>"/></td>
      <td>
        <a href="<?=
        $this->appBaseUri() ?>/translations/<?= $pending->rowKey ?>">
          <?= $pending->english ?>
        </a>
      </td>
      <td contenteditable="true"
          class="foreign-text" data-rowkey="<?= $pending->rowKey ?>"
          data-lang="<?= $pending->lang ?>">
        <?= $pending->translation ?>
      </td>
      <td>
        <a href="<?=
        $this->appBaseUri(
        ) ?>/approve/<?= $pending->rowKey ?>/<?= $pending->lang ?>"
           class="btn btn-success">
          <i class="icon-ok icon-white"></i>
        </a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
