<?php
/**
 * @author: oke.ugwu
 *        Application: Projects
 * @var $this \Sidekick\Applications\Diffuse\Views\Hosts\HostsIndex
 */
?>
<h1>Deployment Hosts</h1>
<a href="<?= $this->baseUri() . '/create'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create Host</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Host Name</th>
    <th>Group</th>
    <th>Ipv 4</th>
    <th>Ipv 6</th>
    <th>SSH Port</th>
    <th></th>
  </tr>
  <?php foreach($this->getHosts() as $host): ?>
    <tr>
      <td><?= $host->hostname; ?></td>
      <td><?= $host->name; ?></td>
      <td><?= $host->ipv4; ?></td>
      <td><?= $host->ipv6; ?></td>
      <td><?= $host->sshPort; ?></td>
      <td>
        <a href="<?= $this->baseUri() . '/' .  $host->id(); ?>/edit"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="<?= $this->baseUri() . '/' .  $host->id(); ?>/delete"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
