<?php
/**
 * Author: oke.ugwu
 * Date: 04/07/13 11:55
 *
 * @var $this \Sidekick\Applications\Diffuse\Views\HostPage
 */
?>
<h1><?= $this->host->name; ?></h1>
<div class="well">
  <p>Name: <?= $this->host->name; ?></p>

  <p>Host Name: <?= $this->host->hostname; ?></p>

  <p>Ipv 4: <?= $this->host->ipv4; ?></p>

  <p>Ipv 6: <?= $this->host->ipv6; ?></p>
</div>
<div>
  <h2>Host Platforms</h2>
  <?php if(count($this->platforms)): ?>
  <div>
    <?= $this->form()->open(); ?>
    <?= $this->form()->token(); ?>
    <?= $this->form()->formNameInput(); ?>
    <?= $this->form()->getElement('serverId'); ?>
    <?= $this->form()->getElement('platformId') ?>
    <?= $this->form()->getElement('submit') ?>
    <?= $this->form()->close() ?>
  </div>
  <?php endif; ?>
  <div>
    <table class="table table-bordered table-condensed">
      <tr>
        <th>Platform Name</th>
        <th></th>
      </tr>
      <?php foreach($this->hostPlatforms as $platform): ?>
        <tr>
          <td><?= $platform->platform()->name ?></td>
          <td>
            <a href="<?= $this->baseUri(
            ) . '/delete-platform/' . $platform->serverId . '/' . $platform->platformId; ?>"
               title="Delete"><i class="icon-trash"></i></a>
          </td>
        </tr>
      <?php endforeach; ?>
    </table>
  </div>
</div>
