build_settings:
    verbose: false
    ignore:
        - "vendor"
        - "Tests"
        - "tests"
        - "public"

notifications:
  email: false

env:
  CUBEX_ENV: development

analyse:
  PhpSuperGlobals:
  Todos:
  PhpLoc:
  PhpLint:
  PhpMessDetection:
  PhpCodeSniffer:
      standard: "Cubex_Code_Standards"

install:
  ComposerCache:
  Command:
    ComposerSelfUpdate: "composer self-update"
    ComposerUpdate: "composer update -o --prefer-dist --no-interaction"

script:
    PhpUnit:
    #Translate:
    #Dispatch:

passed:
  Store:
  ComposerCache:
  #Phuse:

failed:

uninstall:
