<?php
/**
 * Author: oke.ugwu
 * Date: 27/06/13 18:04
 *
 * @var $this \Sidekick\Applications\Evento\Views\EventoTypesIndex
 */
?>
<h1>Events Types</h1>
<a href="<?= $this->baseUri() . '/new'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create Event Type</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>
  <?php foreach($this->eventTypes() as $type): ?>
    <tr>
      <td><?= $type->name ?></td>
      <td><?= $type->description ?></td>
      <td>
        <a href="<?= $this->baseUri() ?>/<?= $type->id(); ?>/edit"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="<?= $this->baseUri() ?>/<?= $type->id(); ?>/delete"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
