<?php
/**
 * Author: oke.ugwu
 * Date: 27/06/13 18:04
 *
 * @var $this \Sidekick\Applications\Evento\Views\EventoIndex
 */
?>
<h1><?= $this->title() ?></h1>
<a href="<?= $this->baseUri() . '/new'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create Event</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(count($this->events())): ?>
  <table class="table table-bordered">
    <?php foreach($this->events() as $event): ?>
      <tr>
        <td>
          <a href="<?= $this->baseUri(); ?>/<?= $event->id() ?>">
            <strong style="font-size:18px;"><?= $event->name ?>
              <?php if($event->closedAt == null): ?>
                [OPEN]
              <?php else: ?>
                [CLOSED]
              <?php endif; ?>
            </strong>

          </a>
          </br>
          <?= $event->description ?>
          </br>
          <strong>Started:</strong> <?= date(
            'd/m/Y H:iA',
            strtotime($event->openedAt)
          ) ?>
          <br/>
          <?php if($event->closedAt == null): ?>
            <strong>Closed:</strong> <?= date(
              'd/m/Y H:iA',
              strtotime($event->closedAt)
            ) ?>
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php else: ?>
  <h3>There no open Events at the moment</h3>
<?php endif; ?>
