<?php
/**
 * Author: oke.ugwu
 * Date: 23/10/13 11:50
 *
 * @var $this \Sidekick\Applications\Evento\Views\EventoTypeForm
 */
?>
<h1><?= $this->title() ?></h1>
<?= $this->form()->open(); ?>
<?= $this->form()->csrfCheck(); ?>
<?= $this->form()->getElement('id'); ?>
<table>
  <tr>
    <td>Name:</td>
  </tr>
  <tr>
    <td><?= $this->form()->getElement('name') ?></td>
  </tr>
  <tr>
    <td>Description:</td>
  </tr>
  <tr>
    <td><?= $this->form()->getElement('description') ?></td>
  </tr>
</table>
<?= $this->form()->getElement('submit') ?>
<?= $this->form()->close(); ?>
