<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 25/07/13
 * Time: 15:54
 * To change this template use File | Settings | File Templates.
 */
?>
<h1>Deployment Stages</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash("msg")->type ?>">
    <?= Session::getFlash('msg')->text ?>
  </div>
<?php endif; ?>
<p class="pull-right"><a class="btn btn-info" href="/diffuse/<?= $this->_projectId ?>/stages/new">Add Deployment Stage</a></p>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <!--<th>Project ID</th>-->
      <th>Platform</th>
      <th>Service Class</th>
      <th>Require All Hosts Passed</th>
      <th>Configuration</th>
      <th>Dependencies</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->getDeploymentStages() as $stage): ?>
    <tr>
      <!--<td><?/*= $stage->projectId */?></td>-->
      <td><?= $stage->platform()->name ?></td>
      <td><?= $stage->serviceClass ?></td>
      <td><?= ($stage->requireAllHostsPass) ? "Yes" : "No" ?></td>
      <td><?= $this->getDetails($stage->configuration)->render(); ?></td>
      <td><?= $this->getDetails($stage->dependencies)->render(); ?></td>
      <td>
        <a href="/diffuse/<?= $stage->projectId ?>/stages/<?= $stage->id ?>/edit"><i class="icon icon-edit"></i></a>
        <a href="/diffuse/<?= $stage->projectId ?>/stages/<?= $stage->id ?>/delete"><i class="icon icon-trash"></i></a>
      </td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
