<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 26/07/13
 * Time: 10:08
 * To change this template use File | Settings | File Templates.
 */
?>
<h1><?= ($this->_stage == null) ? "Add" : "Edit" ?> Deployment Stage</h1>
<?php $form = $this->getForm(); ?>
<?= $form->open(); ?>
<?= $form->token(); ?>
<?= $form->getElement("id")->render(); ?>
<?/*= $form->getElement("project")->render(); */?>
<?= $form->getElement("platform")->render(); ?>
<?= $form->getElement("serviceClass")->render(); ?>
<?= $form->getElement("requireAllHostsPass")->render(); ?>
<p>Configurations</p>
<table class="table table-striped table-bordered table-condensed"
       id="configurationTable">
  <thead>
  <tr>
    <th>Configuration Name</th>
    <th>Configuration Value</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <?php
    if($this->_stage->configuration!=null):
    foreach($this->_stage->configuration as $key => $value):
  ?>
    <tr>
      <td><input type="text" name="configurationKeys[]" value="<?= $key ?>"/></td>
      <td><textarea name="configurationValues[]"><?= $value ?></textarea></td>
      <td>
        <a href="#" class="deleteRow" title="Delete"><i class="icon icon-trash"></i></a>
      </td>
    </tr>
  <?php
    endforeach;
    endif;
  ?>
  </tbody>
</table>
<p class="pull-right">
  <a href="#" id="addConfig"><i class="icon icon-plus"></i> Add Configuration</a>
</p>
<p>Dependencies</p>
<table class="table table-striped table-bordered table-condensed" id="dependencyTable">
  <thead>
  <tr>
    <th>Dependency Name</th>
    <th>Dependency Value</th>
  </tr>
  </thead>
  <tbody>
  <?php
    if($this->_stage->dependencies!=null):
    foreach($this->_stage->dependencies as $key => $value):
  ?>
    <tr>
      <td><input type="text" name="dependencyKeys[]" value="<?= $key ?>"/></td>
      <td><textarea name="dependencyValues[]"><?= $value ?></textarea></td>
      <td>
        <a href="#" class="deleteRow" title="Delete"><i class="icon icon-trash"></i></a>
      </td>
    </tr>
  <?php
    endforeach;
    endif;
  ?>
  </tbody>
</table>
<p class="pull-right">
  <a href="#" id="addDep"><i class="icon icon-plus"></i> Add Dependency</a>
</p>
<?= $form->getElement("submit")->render(); ?>
<?= $form->close(); ?>
