<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 29/07/13
 * Time: 11:30
 * To change this template use File | Settings | File Templates.
 */
?>
<h1>Manage Platform Hosts</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type ?> ">
    <?= Session::getFlash('msg')->text ?>
  </div>
<?php endif; ?>
<p class="pull-right">
  <a class="btn btn-info" href="/diffuse/<?= $this->_projectId ?>/hosts/new">Add Platform Host</a>
</p>
<ul class="nav nav-tabs">
  <?php foreach($this->getPlatforms() as $platform): ?>
    <li><a href="#<?= $platform->name ?>"><?= $platform->name ?></a></li>
  <?php endforeach; ?>
</ul>
<table class="table table-striped table-bordered table-condensed">
  <tbody>
  <?php
  foreach($this->getPlatforms() as $platform):
    $hostplatforms = $this->getHostsForPlatform($platform->id);
    ?>
    <tr class="info" id="<?= $platform->name ?>">
      <td colspan="2"><strong><?= $platform->name ?></strong></td>
    </tr>
    <?php foreach($hostplatforms as $hp): ?>
    <tr>
      <td><?= $this->getHostName($hp->host_id) ?></td>
      <td>
        <a href="/diffuse/<?= $hp->project_id . "/hosts/" . $hp->platform_id . "/" . $hp->host_id ?>/delete">
          <i class="icon icon-trash"></i>
        </a>
      </td>
    </tr>
  <?php
  endforeach;
  endforeach;
  ?>
  </tbody>
</table>
