<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 23/07/13
 * Time: 10:25
 * To change this template use File | Settings | File Templates.
 */
?>
<h1>Version History</h1>
<?= $this->getNav()->render(); ?>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Date</th>
    <th>Deployed By</th>
    <th>Platform</th>
    <th>Comment</th>
    <th>Completed</th>
  </tr>
  </thead>
  <tbody>
  <?php
  $versions = $this->getVersionHistory();
  if(count($versions) > 0):
    foreach($versions as $version): ?>
      <tr>
        <td><?= date('d M Y H:i:s', strtotime($version->createdAt)) ?></td>
        <td><?= $version->user()->display_name ?></td>
        <td><?= $version->platform()->name ?></td>
        <td><?= $version->comment ?></td>
        <td><?= ($version->completed) ? "Yes" : "No" ?></td>
      </tr>
    <?php
    endforeach;
  else:
    ?>
    <tr>
      <td colspan="5">This version has never been deployed</td>
    </tr>
  <?php
  endif;
  ?>
  </tbody>
</table>
