<?php
/**
 * @var $this \Sidekick\Applications\Diffuse\Views\Project\VersionPlatform
 */
?>
<h1 class="pull-right">Status: <span class="text-<?=
  $this->stateClass(
    $this->_state
  ) ?>"><?= $this->_state ?></span></h1>
<h1>Platform: <?php echo $this->_platform->name; ?></h1>
<?= $this->getNav()->render(); ?>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash("msg")->type ?>">
    <?= Session::getFlash('msg')->text ?>
  </div>
<?php endif; ?>
<?php if($this->_state == \Sidekick\Components\Diffuse\Enums\VersionState::REJECTED): ?>
  <div class="alert alert-error">This version has been rejected</div>
<?php endif; ?>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Approval Required From</th>
    <th>Consistency Level</th>
    <th>Required</th>
    <th>Approval Received</th>
  </tr>
  </thead>
  <tbody>
  <?php foreach($this->getApprovalConfiguration() as $approval): ?>
    <tr>
      <td><?= $approval->role ?></td>
      <td><?= $approval->consistency_level ?></td>
      <td><?= ($approval->required) ? "Yes" : "No" ?></td>
      <td><?=
        ($this->isApproved(
          $approval->role,
          $approval->consistency_level
        )) ? "Yes" : "No" ?>
        (<?= $this->getApproverCount($this->_versionID, $approval->role); ?> /
        <?=
        $this->approversRequired(
          $this->_projectID,
          $approval->role,
          $approval->consistency_level
        ); ?>)
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<p>
  <a class="btn btn-info btn-small"
     href="/diffuse/<?= $this->_projectID . "/v/" . $this->_versionID . "/p/" . $this->_platformID; ?>/refresh">Refresh
                                                                                                                Approval
                                                                                                                Status</a>
</p>
<div class="row-fluid">
  <div class="span6">
    <h2>Actions</h2>
    <?= $this->getActionForm()->render() ?>
  </div>
  <div class="span6">
    <h2>Deploy</h2>
    <?= $this->getDeployForm()->render() ?>
  </div>
  <div class="clearfix"></div>
</div>
<h2>Action History</h2>
<?php foreach($this->getActionHistory() as $action): ?>
  <div class="media">
    <a class="pull-left" href="#">
      <img class="media-object"
           src="http://www.gravatar.com/avatar/<?php echo md5(
             strtolower($action->user()->email)
           ); ?>?s=50">
    </a>

    <div class="media-body action-box <?php echo $action->actionType; ?>">
      <h4 class="media-deading">
        <?= $action->user()->displayName ?>
        <small>(<?= $action->user_role ?>)</small>
        <small class="pull-right">
          <?= date("d M Y H:i", strtotime($action->updatedAt)) ?>
        </small>
      </h4>

      <p><?= $action->comment ?></p>
    </div>
  </div>
<?php endforeach; ?>
