<?php
/**
 * Author: oke.ugwu
 * Date: 16/07/13 16:41
 *
 * @var $this \Sidekick\Applications\Phuse\Views\PackagesList
 */
?>
<h1><?= $this->heading ?></h1>
<?= $this->renderFilters() ?>
<table class="table table-striped table-bordered table-condensed">
  <tr class="info">
    <th>Name</th>
    <th>Description</th>
    <?php if($this->showFullList): ?>
      <th>Author</th>
      <th>Version</th>
      <th>License</th>
      <th>Date Created</th>
    <?php endif; ?>
  </tr>
  <?php if($this->packages): ?>
    <?php foreach($this->packages as $package): ?>
      <tr>
        <td>
          <a href="/phuse/view/<?= $package->id() ?>"><?= $package->name; ?></a>
        </td>
        <td><?= $package->description; ?></td>
        <?php if($this->showFullList): ?>
          <td>
            <?php if(is_array($package->authors)): ?>
              <ul>
                <?php foreach($package->authors as $author): ?>
                  <li>
                    <?= $author->name; ?> <?=
                    isset($author->email) ?
                      '&lt;' . $author->email . '&gt;' : ''; ?>
                  </li>
                <?php endforeach; ?>
              </ul>
            <?php else: ?>
              -
            <?php endif; ?>
          </td>
          <td><?= $package->release()->version; ?></td>
          <td><?= ($package->license != '') ? $package->license : '-'; ?></td>
          <td><?= date('d M y H:i:s', strtotime($package->createdAt)); ?></td>
        <?php endif; ?>
      </tr>
    <?php endforeach; ?>
  <?php endif; ?>
</table>
