<?php
/**
 * @author: brooke.bryan
 *        Application: Phuse
 * @var $this \Sidekick\Applications\Phuse\Views\PackageView
 *
 * @link  https://packagist.org/packages/cubex/cubex
 */
?>
<div class="page-header">
  <h2><?= $this->getPackage()->name; ?>
    <?php if($this->getPackage()->version !== null): ?>
      <small>v<?= $this->getPackage()->version; ?></small>
    <?php endif; ?>
  </h2>
</div>
<div class="well">
  <p><?= $this->getPackage()->description; ?></p>

  <p><strong>License:</strong> <?= $this->getPackage()->license; ?></p>
</div>
<div class="row-fluid">
  <div class="well span4">
    <h3>Authors</h3>
    <?php if($this->getPackage()->authors !== null): ?>
      <ul>
        <?php foreach($this->getPackage()->authors as $author): ?>
          <li>
            <?= $author->name; ?> <?= isset($author->email) ? '&lt;' . $author->email . '&gt;' : ''; ?>
          </li>
        <?php endforeach; ?>
      </ul>
    <?php else: ?>
      Information not available
    <?php endif; ?>
  </div>

  <div class="well span4">
    <h3>Requires</h3>
    <?php if($this->getPackage()->require !== null): ?>
      <ul>
        <?php foreach($this->getPackage()->require as $package => $require): ?>
          <li><a
              href="https://packagist.org/packages/<?= $package ?>"
              target="_blank"><?= $package ?></a>:
            <?= $require; ?>
          </li>
        <?php endforeach; ?>
      </ul>
    <?php else: ?>
      Information not available
    <?php endif; ?>
  </div>

  <div class="well span4">
    <h3>Releases</h3>
    <?php if($this->getReleases() !== null): ?>
      <?php foreach($this->getReleases() as $release): ?>
        <strong><?php echo $release->version; ?></strong>
        <div>
          <p>require: <code>"<?php echo $this->getPackage()->name; ?>" :
                            "<?php echo $release->version; ?>"</code></p>

          <p>Last Updated: <?php echo date(
              'd/M/Y H:i',
              strtotime($release->updatedAt)
            ); ?></p>

          <p>Reference: <?php echo substr($release->zipHash, 0, 6); ?></p>
        </div>
      <?php endforeach; ?>
    <?php else: ?>
      No releases made yet
    <?php endif; ?>
  </div>
</div>
<?php if($this->getPackage()->projectId !== null): ?>
  <p>
    <a href="/P<?= $this->getPackage()->projectId ?>/scripture//README">View
                                                                         Documentation</a>
  </p>
<?php endif; ?>
