<?php
/**
 * @author: brooke.bryan
 *        Application: Phuse
 * @var $this \Sidekick\Applications\Phuse\Views\PackageView
 *
 * @link  https://packagist.org/packages/cubex/cubex
 */
?>
<h2>PACKAGE/NAME</h2>
<p>Description goes here</p>

<fieldset>
  <legend>dev-master</legend>
  <div>
    <p>require: <code>"package/name" : "dev-master"</code></p>

    <p>Last Updated: XXX</p>

    <p>Reference: XXX</p>
  </div>
</fieldset>

<fieldset>
  <legend>Versions 1.0.0</legend>
  <div>
    <p>require: <code>"package/name" : "1.0.0"</code></p>

    <p>Last Updated: XXX</p>

    <p>Reference: XXX</p>
  </div>
</fieldset>

<p><a href="/scripture/1/README">View Documentation</a></p>

