<?php
/**
 * Created by JetBrains PhpStorm.
 * User: oke.ugwu
 * Date: 31/05/13
 * Time: 12:45
 * To change this template use File | Settings | File Templates.
 *
 * @var $this \Sidekick\Applications\Phuse\Views\PackageResults
 */
?>
<?php if(count($this->getPackages())): ?>
  <?php foreach($this->getPackages() as $package): ?>
    <div class="phuse-result well">
      <h3><a href="<?= $this->appBaseUri() . '/view/' . $package->id; ?>">
          <?= $package->name; ?></a>
      </h3>

      <p><?= $package->description; ?></p>

      <p><strong>Authors:</strong><br>
        <?php $authors = $package->authors; ?>
        <?php if($authors !== null): ?>
          <?php foreach($authors as $author): ?>
            <strong><?= $author->name; ?></strong>
            <?= (next($authors)) ? ',' : '' ?>
          <?php endforeach; ?>
        <?php else: ?>
          Information not available
        <?php endif; ?>
      </p>
    </div>
  <?php endforeach; ?>
<?php else: ?>
  <div class="phuse-result well">
    <p>No packages found</p>
  </div>
<?php endif; ?>
