<?php
/**
 * @author: brooke.bryan
 *        Application: Phuse
 * @var $this \Sidekick\Applications\Phuse\Views\PackageView
 *
 * @link  https://packagist.org/packages/cubex/cubex
 */
?>
<h2><?php echo $this->package->name; ?></h2>
<p><?php echo $this->package->description; ?></p>

<?php foreach($this->releases as $release): ?>
<fieldset>
  <legend><?php echo $release->version; ?></legend>
  <div>
    <p>require: <code>"<?php echo $this->package->name; ?>" : "<?php echo $release->version; ?>"</code></p>

    <p>Last Updated: <?php echo date('d/M/Y H:i', strtotime($release->updatedAt)); ?></p>

    <p>Reference: <?php echo substr($release->zipHash, 0, 6); ?></p>
  </div>
</fieldset>
<?php endforeach; ?>
<p><a href="/scripture/1/README">View Documentation</a></p>

