<?php
/**
 * Created by JetBrains PhpStorm.
 * User: oke.ugwu
 * Date: 31/05/13
 * Time: 11:43
 * var $this \Sidekick\Applications\Phuse\Views\PhuseIndex
 */
?>
<div class="well alert-info">
  <p>Phuse is a package manager for your private code repositories.</p>

  <p>Versioning of packages is handled through Diffuse,
     and dev builds can be built into your fortify builds.</p>
</div>

<input class="input-block-level phuse-search" type="text"
       placeholder="Seek and you shall find...">

<div class="phuse-results well">
</div>

<div class="well">
  <h3>Getting Started</h3>

  <div class="row-fluid">

    <div class="span6">
      <span class="lead">Thou shall install composer</span>

      <p>Run this in your command line:</p>
      <code>curl -s http://getcomposer.org/installer | php</code>

      <p><br/>Or download composer.phar into your project root.</p>

      <p>Put a file named composer.json at the root of your project,
         containing your project dependencies:</p>
    </div>

    <div class="span6">
      <span class="lead">...and add Phuse the repository</span>

      <p>Put a file named composer.json at the root of your project,
         containing your project dependencies:</p>

      <p><span class="label label-important">Important!</span>
        Add the following line to composer.json</p>

      <code class="pre">"repositories": [{
                 "type": "composer",
                 "url": "http://phuse.<?php echo $this->baseUri; ?>/"
                 }]</code>
    </div>

  </div>
</div>
