<?php
/**
 * Author: oke.ugwu
 * Date: 16/07/13 17:47
 *
 * @var $this \Sidekick\Applications\Phuse\Views\RecentReleases
 */
?>
<h1>Recent Releases</h1>
<table class="table table-striped table-bordered table-condensed">
  <tr class="info">
    <th>Package</th>
    <th>Version</th>
    <th>Date Created</th>
  </tr>
  <?php if($this->releases): ?>
    <?php foreach($this->releases as $release): ?>
      <tr>
        <td>
          <a href="/phuse/view/<?= $release->package()->id() ?>">
            <?= $release->package()->name; ?>
          </a>
        </td>
        <td><?= $release->version; ?></td>
        <td><?= date('d M y H:i:s', strtotime($release->createdAt)); ?></td>
      </tr>
    <?php endforeach; ?>
  <?php endif; ?>
</table>
