<?php
/**
 * @author: oke.ugwu
 *        Application: Configurator
 * @var $this \Sidekick\Applications\Configurator\Views\ConfigGroupView
 */
?>
<h1>Config Groups</h1>
<?php echo $this->getBreadcrumbs(); ?>
<div class="row-fluid">
  <div class="span5 well">
    <h3>Add New Group</h3>
    <?php echo $this->form(); ?>
  </div>
  <div class="span5 well">
    <h3>Groups</h3>

    <p class="muted"><em>Click on group name to add items to group</em></p>
    <?php foreach($this->configGroups as $group): ?>
      <li>
        <a href="<?php echo $this->baseUri(
        ); ?>/config-items/<?php echo $group->id; ?>">
          <?php echo $group->groupName; ?>
        </a>
      </li>
    <?php endforeach; ?>
  </div>

</div>
