<?php
/**
 * @author: oke.ugwu
 *        Application: Configurator/Views
 * @var $this \Sidekick\Applications\Configurator\Views\ConfigItemsManager
 */
?>
<h1>Config Items</h1>
<?php if(Session::getFlash('msg')): ?>
<div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
  <?php echo Session::getFlash('msg')->text; ?>
</div>
<?php endif; ?>
<?php echo $this->getBreadcrumbs(); ?>
<p><em>For multi items specify values like this a,b,c. For multi keyed specify
       values like a=1,b=2,c=3</em></p>

<?php if($this->itemInUse): ?>
  <div class="alert alert-block" style="width:800px;">
    <h4>Warning</h4>

    <p>Some projects already use this item. Deleting it means every project
       that use this item will no longer have it in their config</p>

    <p><a href="<?php echo $this->baseUri() .
        '/config-items/' .
        $this->configGroup->id(); ?>">
        Don't delete
      </a> |
      <a href='<?php echo $this->baseUri() .
        '/remove-config-item/' .
        $this->itemInUse; ?>/force'>
        Go ahead and delete it
      </a>
    </p></div>
<?php endif; ?>

<!--Add Config Item Form-->
<div class="well">
<?php
echo $this->addForm()->open();
echo $this->addForm()->token();
echo $this->addForm()->formNameInput();
?>
<?php echo $this->addForm()->getElement('groupId'); ?>
<table>
  <tr>
    <td>Key</td>
    <td>Type</td>
    <td>Value</td>
    <td></td>
  </tr>
  <tr>
    <td><?php echo $this->addForm()->getElement("key"); ?></td>
    <td><?php echo $this->addForm()->getElement("type"); ?></td>
    <td><?php echo $this->addForm()->getElement("value"); ?></td>
    <td></td>
  </tr>
</table>
<?php echo $this->addForm()->getElement('submit'); ?>
<?php echo $this->addForm()->close(); ?>
</div>

<!--Update Config Items Form-->
<div class="well">
<?php
echo $this->updateForm()->open();
echo $this->updateForm()->token();
echo $this->updateForm()->formNameInput();
?>
<?php echo $this->updateForm()->getElement('groupId'); ?>
<table>
  <tr>
    <td>Key</td>
    <td>Type</td>
    <td>Value</td>
    <td></td>
  </tr>
  <?php foreach($this->configItems as $item): ?>
    <tr>
      <td><?php echo $this->updateForm()->getElement("kv[$item->id][key]"); ?></td>
      <td><?php echo $this->updateForm()->getElement("kv[$item->id][type]"); ?></td>
      <td><?php echo $this->updateForm()->getElement("kv[$item->id][value]"); ?></td>
      <td>
        <a href="<?php echo $this->baseUri() .
          '/remove-config-item/' . $item->id ?>"
           class="text-error">&times;</a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
<?php echo $this->updateForm()->getElement('submit'); ?>
<?php echo $this->updateForm()->close(); ?>
</div>


