<?php
/**
 * @author: oke.ugwu
 * Application: Configurator
 * @var $this \Sidekick\Applications\Configurator\Views\ConfigGroupView
 */
?>
<h1 class="breadcrumbs">
  <a href='/configurator'>All Projects</a> /
  <?php if($this->parentProject->exists()): ?>
  <a href="/configurator/project/<?php echo $this->parentProject->id(); ?>">
    <?php echo $this->parentProject->name; ?>
  </a> /
  <?php endif; ?>
  <?php echo $this->project->name; ?> <span class="muted">Config Groups</span>
</h1>
<div class="row-fluid">
  <div class="span5 well">
    <h3>Add New Group</h3>
    <?php echo $this->form(); ?>
  </div>
  <div class="span5 well">
    <h3>Groups</h3>
    <p class="muted"><em>Click on group name to add items to group</em></p>
    <?php foreach($this->configGroups as $group): ?>
      <li>
        <a href="/configurator/config-items/<?php echo $group->id; ?>">
          <?php echo $group->groupName; ?>
        </a>
      </li>
    <?php endforeach; ?>
  </div>

</div>
