<?php
/**
 * @author: oke.ugwu
 * Application: Configurator\Views
 * @var $this \Sidekick\Applications\Configurator\Views\ProjectConfigurator
 */
?>

<h1><?php echo $this->project->name; ?>
  <?php echo ($this->currentEnvironment->exists()) ? ' > ' . ucwords(
    $this->currentEnvironment->name
  ) : ""; ?>
</h1>
<?php foreach($this->environments as $env): ?>
  <p style='float:left; margin-right:10px;'>
    <a href="/configurator/project-configs/<?php echo $this->project->id(
    ); ?>/<?php echo $env->id(); ?>">
      <?php echo ucwords($env->name); ?>
    </a></p>
<?php endforeach; ?>
<div class="clearfix"></div>

<div class="row-fluid">
  <div class="span7 well">
    <h3>Available Config</h3>

    <?php if(count($this->availableConfigs)): ?>
      <?php foreach($this->availableConfigs as $groupName => $configItems): ?>
        <div class="config-group">
          <p><b><?php echo $groupName; ?></b></p>
          <?php if($configItems->count() > 0): ?>

            <div style="width:450px;">
              <?php foreach($configItems as $item): ?>
                <p style="width:100%;word-wrap:break-word;margin:0;">
                  <small>
                    [<a
                    href="/configurator/add-project-config-item/<?php echo $this->project->id(
                    ) . '/' . $this->currentEnvironment->id(
                    ) . '/' . $item->id; ?>"
                    style="color:green; font-weight:bold; font-size:12px;">+</a>]

                    <?php echo "$item->key = <b>" . $item->prepValueOut(
                      $item->value, $item->type
                    ) . "</b>"; ?>
                  </small>
                </p>
              <?php endforeach; ?>
            </div>
          <?php endif; ?>
        </div>
      <?php endforeach; ?>
    <?php else: ?>
      <p class="text-error">
        <small>This project has no config groups/items setup yet, you need to
          create
          some config groups first. Config group help you group you individual
          configuration key and value pair
        </small>
      </p>

      <p><a
        href="/configurator/config-groups/<?php echo $this->project->id(); ?>"
        class="btn btn-primary pull-right preview-ini">Add Config</a></p>
    <?php endif; ?>


  </div>
  <div class="span3 well">
    <h3>Your <?php echo ucwords($this->currentEnvironment->name) ?> Config</h3>
    <?php foreach($this->environmentConfig as $groupName => $items): ?>
      <div style="margin-bottom:5px;">
        <p style="margin:0;"><b><?php echo $groupName; ?></b></p>

        <?php foreach($items as $itemObj): ?>
          <p style="width:100%;word-wrap:break-word;margin:0;">
            <small>
              [<a
              href="/configurator/modify-project-config-item/<?php echo $this->project->id(
              ) . "/" . $this->currentEnvironment->id(
              ) . "/" . $itemObj->id; ?>"
              style="color:blue; font-weight:bold; font-size:12px;">...</a>]
              [<a
              href="/configurator/remove-project-config-item/<?php echo $this->project->id(
              ) . "/" . $this->currentEnvironment->id() . "/" .
              $itemObj->id; ?>"
              style="color:red; font-weight:bold; font-size:12px;">x</a>]

              <?php echo "$itemObj->key = <b>" . $itemObj->prepValueOut(
                $itemObj->value, $itemObj->type
              ) . "</b>"; ?>
            </small>
          </p>
        <?php endforeach; ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>
