<?php
/**
 * @author: oke.ugwu
 *        Application: Configurator/Templates
 * @var $this \Sidekick\Applications\Configurator\Views\ProjectList
 */
?>
<h1 class="breadcrumbs">
  <?php if($this->getParentProject() !== null): ?>
    <a href="<?php echo $this->baseUri(); ?>">All Projects</a> /
    <?php echo $this->getParentProject()->name; ?>
  <?php else: ?>
    All Projects
  <?php endif; ?>
</h1>
<p class="muted"><em>Manage configurations across all your projects!</em></p>
<?php foreach($this->getProjects() as $project): ?>
  <div class="well boxed">
    <?php if($this->getSubProjectsCount($project->id) > 0): ?>
      <h3>
        <a href="<?php echo $this->baseUri(); ?>/project/<?php echo $project->id; ?>">
          <?php echo $project->name; ?>
        </a>
      </h3>
    <?php else: ?>
      <h3><?php echo $project->name; ?></h3>
    <?php endif; ?>
    <p>
      <?php if($this->getSubProjectsCount($project->id) > 0): ?>
        <small>
          <?php echo $this->getSubProjectsCount($project->id); ?> Sub Projects
        </small>
      <?php else: ?>
        <small>No Sub Projects</small>
      <?php endif; ?>,
      <small>
        <?php echo ($this->getConfigGroupsCount($project->id) > 0) ?
          $this->getConfigGroupsCount($project->id) : 'No' ?>
        Config Groups
      </small>
    </p>

    <?php if($this->getConfigGroupsCount($project->id) == 0): ?>
      <p class="text-error">
        <small>
          This project has no config groups setup yet, you need to create
          some config groups first.
        </small>
      </p>
    <?php endif; ?>



    <p style="margin-top:10px;">

      <a href="<?php echo $this->baseUri(); ?>/config-groups/<?php echo $project->id; ?>"
         class="btn btn-primary">
        Config Groups
      </a>

      <a href="<?php echo $this->baseUri(); ?>/project-configs/<?php echo $project->id; ?>/"
         class="btn btn-primary">Configure</a>

      <a href="<?php echo $this->baseUri(); ?>/build-ini/<?php echo $project->id; ?>/"
         class="btn btn-primary">Preview ini</a>
    </p>

    <div style="clear:both;"></div>
  </div>
<?php endforeach; ?>


