<?php
/**
 * @author: oke.ugwu
 *        Application: Configurator\Views
 * @var $this \Sidekick\Applications\Configurator\Views\ProjectConfigurator
 */
?>

<h1>Configure</h1>
<?php echo $this->getBreadcrumbs(); ?>
<?php foreach($this->environments as $env): ?>
  <p style='float:left; margin-right:10px;'>
    <a href="<?php echo $this->baseUri() .
      '/project-configs/' .
      $this->project->id() . '/' . $env->id(); ?>"
      <?php if($env->id() == $this->currentEnvironment->id()): ?>
        class="label label-warning"
      <?php endif; ?>
      >
      <?php echo ucwords($env->name); ?>
    </a></p>
<?php endforeach; ?>
<div class="clearfix"></div>

<div class="row-fluid">
  <div class="span8 well">
    <h3>Available Config</h3>
    <?php if(count($this->availableConfigs)): ?>
      <?php foreach($this->availableConfigs as $groupName => $configItems): ?>
        <div class="config-group">
          <p><b><?php echo $groupName; ?></b></p>
          <?php if($configItems->count() > 0): ?>

            <div style="width:450px;">
              <?php foreach($configItems as $item): ?>
                <p style="width:100%;word-wrap:break-word;margin:0;">
                  <small>
                    [<a href="<?php echo $this->baseUri() .
                      '/add-project-config-item/' .
                      $this->project->id() .
                      '/' . $this->currentEnvironment->id() .
                      '/' . $item->id; ?>"
                        class="text-success">+</a>]

                    <?php echo "$item->key = <b>" .
                      $item->prepValueOut($item->value, $item->type) .
                      "</b>"; ?>
                  </small>
                </p>
              <?php endforeach; ?>
            </div>
          <?php endif; ?>
        </div>
      <?php endforeach; ?>
    <?php else: ?>
      <p class="text-error">
        <small>
          This project has no config groups/items setup yet, you need to
          create some config groups first.
        </small>
      </p>

      <p><a href="<?php echo $this->baseUri() .
          '/config-groups/' .
          $this->project->id(); ?>"
            class="btn btn-primary pull-right preview-ini">Add Config</a></p>
    <?php endif; ?>


  </div>
  <div class="span4 well">
    <h3><?php echo ucwords($this->currentEnvironment->name) ?> Config</h3>
    <?php foreach($this->environmentConfig as $groupName => $items): ?>
      <div style="margin-bottom:5px;">
        <p style="margin:0;"><b><?php echo $groupName; ?></b></p>

        <?php foreach($items as $itemObj): ?>
          <p style="width:100%;word-wrap:break-word;margin:0;">
            <small>
              [<a
                href="<?php echo $this->baseUri() .
                  '/modify-project-config-item/' .
                  $this->project->id() .
                  "/" . $this->currentEnvironment->id() .
                  "/" . $itemObj->id; ?>"
                class="text-info">...</a>]
              [<a href="<?php echo $this->baseUri() .
                '/remove-project-config-item/' .
                $this->project->id() . "/" .
                $this->currentEnvironment->id() . "/" . $itemObj->id; ?>"
                  class="text-error">&times;</a>]

              <?php echo "$itemObj->key = <b>" .
                $itemObj->prepValueOut($itemObj->value, $itemObj->type) .
                "</b>"; ?>
            </small>
          </p>
        <?php endforeach; ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>
