<?php
/**
 * @var $this Sidekick\Applications\Diffuse\Views\Projects\OverviewView
 */
use \Sidekick\Applications\Diffuse\Views\Projects\Versions\VersionsViewHelper;

?>
<div class="navbar">
  <div class="navbar-inner">
    <a href="#" class="brand"><?= $this->project()->name; ?> Versions</a>
    <ul class="nav">
      <li>
        <a href="<?= $this->baseUri(); ?>/configuration/approval">
          Approval Configuration</a>
      </li>
      <li>
        <a href="<?= $this->baseUri(); ?>/configuration/deployment/stages">
          Deployment Stages</a>
      </li>
      <li>
        <a href="<?= $this->baseUri(); ?>/configuration/deployment/hosts">
          Deployment Hosts</a>
      </li>
    </ul>
  </div>
</div>

<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>

<?php if($this->versions()->hasMappers()): ?>

  <table class="table table-striped table-bordered table-condensed">
    <thead>
    <tr>
      <th>Version</th>
      <th>Status</th>
      <th>Commit Range</th>
      <?php foreach($this->platforms() as $platform): ?>
        <th><?= ucwords($platform->name); ?></th>
      <?php endforeach; ?>
      <th>Created</th>
      <th>Last Updated</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->versions() as $version): ?>
      <tr>
        <td><strong><a
            href="<?= $this->baseUri(); ?>/v/<?=
            $version->id();
            ?>"><?= $version->format(); ?></a>
          </strong></td>
        <td><?= VersionsViewHelper::colourState($version->versionState); ?></td>
        <td><?= substr($version->fromCommitHash, 0, 6); ?> -
          <?= substr($version->toCommitHash, 0, 6); ?></td>
        <?php foreach($this->platforms() as $platform): ?>
          <td>
            <a href="<?= $this->baseUri(); ?>/v/<?=
            $version->id(); ?>/p/<?= $platform->id(); ?>">
              <?=
              VersionsViewHelper::colourState(
                $version->platformStates()->getById(
                  [$platform->id(), $version->id()]
                )->state
              );
              ?></a>
          </td>
        <?php endforeach; ?>
        <td><?= date('d M Y H:i', strtotime($version->createdAt)); ?></td>
        <td><?= date('d M Y H:i', strtotime($version->updatedAt)); ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

<?php else: ?>

  No versions exist for this project yet.  Please run a relevant build.

<?php endif ?>
