<?php
/**
 * Author: oke.ugwu
 * Date: 27/08/13 16:19
 * @var $this \Sidekick\Applications\Diffuse\Views\Projects\Configuration\DeploymentConfigurationOptions
 */
?>
<?php if(count($this->getConfigurationOptions())): ?>
  <p>Configurations</p>
  <table class="table table-striped table-bordered table-condensed">
    <thead>
    <tr>
      <th></th>
      <th>Configuration Name</th>
      <th>Configuration Value</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->getConfigurationOptions() as $key => $value): ?>
      <tr>
        <td>
          <input type="checkbox"
                 class="config-value-toggle"
                 data-config-id="<?= $key ?>-value"
            <?= $this->checked($key); ?> />
        </td>
        <td><?= $key ?></td>
        <td>
          <textarea id="<?= $key ?>-value"
                    name="configuration[<?= $key ?>]"
                    placeholder="<?= $value ?>"
            <?= $this->disabled($key) ?>
            ><?= $this->configurationValue($key) ?></textarea>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
<?php endif; ?>
