<?php
/**
 * @var $this Sidekick\Applications\Diffuse\Views\Projects\Configuration\DeploymentConfigStepsView
 */
?>
<h2><?= \Cubex\Helpers\Strings::titleize($this->platform()->name) ?>: Configuration Steps</h2>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>
<p class="pull-right">
  <a class="btn btn-success"
     href="/<?= $this->baseUri() ?>/new">
    <i class="icon-white icon-plus"></i> Add Deployment Step</a>
</p>
<?php $platform = $this->platform() ?>
  <table class="table table-striped table-bordered table-condensed">
    <thead>
    <tr>
      <th>Name</th>
      <th>Command</th>
      <th>Order</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->deploymentSteps($platform->id()) as $step): ?>
      <tr>
        <td><?= $step->name; ?></td>
        <td><?= $step->command ?></td>
        <td>
          <?php if($step->order > 1): ?>
            <a href="/<?= $this->baseUri(
            ) ?>/<?= $step->id ?>/<?= $step->platformId ?>/order/up"
               class="btn" style="display:block; width:10px;">
              <i class="icon icon-arrow-up"></i></a>
          <?php endif; ?>
          <?php if($step->order != $this->deploymentSteps($platform->id())->count()): ?>
            <a href="/<?= $this->baseUri(
            ) ?>/<?= $step->id ?>/<?= $step->platformId ?>/order/down"
               class="btn" style="display:block; width:10px;">
              <i class="icon icon-arrow-down"></i></a>
          <?php endif; ?>
        </td>
        <td>
          <a href="/<?= $this->baseUri() ?>/<?= $step->id ?>/edit"><i
              class="icon icon-edit"></i></a>
          <a href="/<?= $this->baseUri() ?>/<?= $step->id ?>/delete"><i
              class="icon icon-trash"></i></a>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
