<?php
/**
 * Author: oke.ugwu
 * Date: 02/07/13 17:16
 *
 * @var $this \Sidekick\Applications\Diffuse\Views\ApprovalConfigurationPage
 */
?>
<h1>Approval Configuration</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>

<a class="btn btn-success pull-right" id="addConfigBtn"> <i
    class="icon-plus icon-white"></i>
  Add Config</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<div class="well hide" id="approveForm">
  <?php
  echo $this->form()->open();
  echo $this->form()->token();
  echo $this->form()->formNameInput();
  echo $this->form()->getElement('projectId');
  ?>
  <table>
    <tr>
      <td>Role</td>
      <td>
        <?= $this->form()->getElement('role') ?>
      </td>
    </tr>
    <tr>
      <td>Consisteny Level</td>
      <td>
        <?= $this->form()->getElement('consistencyLevel') ?>
      </td>
    </tr>
    <tr>
      <td>Required</td>
      <td>
        <?= $this->form()->getElement('required') ?>
      </td>
    </tr>
  </table>
  <?= $this->form()->getElement('submit') ?>
  <button class="btn" id="cancelBtn">Cancel</button>
  <?= $this->form()->close() ?>
</div>

<table class="table table-bordered table-hover">
  <tr>
    <th>Role</th>
    <th>Consistency Level</th>
    <th>Required</th>
    <th></th>
  </tr>
  <?php foreach($this->getConfig() as $config): ?>
    <?php $id = md5($config->id()); ?>
    <?php $editForm = $this->editForm($config->projectId, $config->role); ?>
    <tr>
      <td>
        <div class="role<?= $id ?>">
          <?= ucfirst($config->role) ?>
        </div>
        <div class="role<?= $id ?> hide">
          <?= $editForm->getElement('role') ?>
        </div>
      </td>
      <td>
        <div class="<?= $id ?> <?= $id ?>">
          <?= strtoupper($config->consistencyLevel) ?>
        </div>
        <div class="<?= $id ?> hide">
          <?=
          $editForm->getElement('consistencyLevel')
          ->addAttribute('class', 'input-small') ?>
        </div>
      </td>
      <td>
        <div class="<?= $id ?> <?= $id ?>">
          <?= ($config->required) ? 'Yes' : 'No' ?>
        </div>
        <div class="<?= $id ?> hide">
          <?= $editForm->getElement('required') ?>
        </div>
      </td>
      <td>
        <a title="Edit" onclick="$('.<?= $id ?>').toggle();"><i
            class="icon-edit"></i></a>
        <a
          href="/diffuse/approval/<?= $this->projectId . '/' . $config->role ?>/delete">
          <i class="icon icon-trash"></i>
        </a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
