<?php
/**
 * Author: oke.ugwu
 * Date: 02/07/13 17:16
 *
 * @var $this \Sidekick\Applications\Diffuse\Views\ApprovalConfigurationPage
 */
?>
<h1>Approval Configuration</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Role</th>
    <th>Consistency</th>
    <th>Required</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <?php foreach($this->getPlatforms() as $platform): ?>
    <tr class="info">
      <td colspan="3"><strong><?= $platform->name ?></strong></td>
      <td><a href="/diffuse/approval/<?= $this->projectId . "/" . $platform->id ?>" title="Create"><i class="icon-plus"></i></a></td>
    </tr>
    <?php
      $ac = $this->getConfigurations($platform->id);
      if($ac->count()==0):
    ?>
    <tr>
      <td colspan="4">No configurations exists for this platform</td>
    </tr>
    <?php
      else:
      foreach($ac as $a):
    ?>
      <tr>
        <td><?= $a->role ?></td>
        <td><?= $a->consistency_level ?></td>
        <td><?= ($a->required) ? "Yes" : "No" ?></td>
        <td><a href="<?= $this->projectId . "/" . $platform->id . "/" . $a->role ?>/delete" title="Delete"><i class="icon-trash"></i></a></td>
      </tr>
    <?php
       endforeach;
      endif;
    endforeach;
    ?>
  </tbody>
</table>
