<?php
/**
 * Author: oke.ugwu
 * Date: 02/07/13 17:16
 *
 * @var $this \Sidekick\Applications\Diffuse\Views\ApprovalConfigurationPage
 */
?>
<h1>Approval Configuration</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Platform</th>
    <th>Role</th>
    <th>Consistency</th>
    <th>Required</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <?php
  $platforms = $this->getPlatforms();
  foreach($platforms as $platform)
  {
    $ac = $this->getConfigurations($platform->id);
    $c  = count($ac);
    echo "<tr><td";
    if($c > 1)
    {
      echo " rowspan='$c'";
    }
    echo ">" . $platform->name . "</td>";
    if($c == 0)
    {
      echo "<td colspan='3'>No configurations exists for this platform</td>";
      echo "<td><a href='/diffuse/approval/" . $this->projectId . "/" . $platform->id . "' title='Create'><i class='icon-plus'></i></a></td>";
      echo "</tr>";
    }
    else
    {
      $i = 0;
      foreach($ac as $a)
      {
        echo "<td>" . $a->role . "</td>";
        echo "<td>" . $a->consistency_level . "</td>";
        echo "<td>";
        echo ($a->required) ? "Yes" : "No";
        echo "</td>";
        echo "<td>";
        if($i == 0)
        {
          echo "<a href='/diffuse/approval/" . $this->projectId . "/" . $platform->id . "' title='Create'><i class='icon-plus'></i></a> ";
        }
        echo "<a href='" . $this->projectId . "/" . $platform->id . "/" . $a->role . "/delete' title='Delete'><i class='icon-trash'></i></a></td>";
        echo "</tr>";
        if($i < ($c - 1))
        {
          echo "<tr>";
        }
        $i++;
      }
    }
  }
  ?>
  </tbody>
</table>
