<?php
/**
 * @author: oke.ugwu
 *        Application: Projects
 * @var $this \Sidekick\Applications\Diffuse\Views\Platforms\DeploymentConfigurationIndex
 */
?>
<h1>Deployment Configuration</h1>
<a href="<?= $this->baseUri() . '/create'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create Configuration</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info ">
    <th>Name</th>
    <th>Description</th>
    <th>Last Update</th> 
  </tr>
  <?php foreach($this->getDeploymentConfigs() as $config): ?>
    <tr class="">
      <td>
       <?= $config->name; ?>
        <div class="pull-right actions">
        <a href="/diffuse/manage-configs/<?= $config->id() ?>/steps"><i class="icon-plus"></i> Edit Steps </a> |
        <a href="<?= $this->baseUri() . '/' . $config->id; ?>/edit"
           title="Edit"><i class="icon-edit"></i> Edit</a> |
        <a href="<?= $this->baseUri() . '/' . $config->id; ?>/delete"
           title="Delete"><i class="icon-trash"></i> Delete</a>
        </div>
      </td>
      <td class=""><?= $config->description; ?></td>
      <td class=""><?= date('d/M/Y', strtotime($config->updated_at)); ?></td>

    </tr>
  <?php endforeach; ?>
</table> 
