<?php
/**
 * Author: oke.ugwu
 * Date: 28/08/13 18:25
 * @var $this \Sidekick\Applications\Diffuse\Views\DeploymentsView
 */
?>
<h2>Deployments <?= $this->getProject() ? 'For ' . $this->getProject()->name : ''; ?></h2>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>

<table class="table table-striped table-bordered">
  <tr>
    <th> </th>
    <th>Build Number</th>
    <th>Branch</th>
    <th>Hosts</th>
    <th>Status</th>
    <th>User</th>
    <th>Date</th>
  </tr>
  <?php
  /***
   * @var $deplyment \Sidekick\Components\Diffuse\Mappers\Deployment
   */

  foreach($this->getDeploymentlist() as $deplyment)
  {
    $project = new \Sidekick\Components\Projects\Mappers\Project($deplyment->projectId);
    $b = new \Sidekick\Components\Fortify\Mappers\BuildRun($deplyment->buildId);
    $user = new \Sidekick\Components\Users\Mappers\User($deplyment->userId);
    $hosts = json_decode($deplyment->hosts);
    $hostnames = [];

    if($hosts)
    {
      foreach($hosts as $h)
      {
        $host = new \Sidekick\Components\Servers\Mappers\Server($h);
        $hostnames[] = $host->hostname;
      }
    }

    ?>
    <tr class="<?= $this->textClass($deplyment);  ?>">
      <td>
        <?php $exploded = explode(":", $project->name); ?>
        <span class="label label-info"><?= isset($exploded[1]) ? $exploded[0] : ''; ?></span>&nbsp;&nbsp;
        <?php $link = $this->getProject() ? "/P$deplyment->projectId/diffuse/deployments/$deplyment->id/logs" : "/P$deplyment->projectId/diffuse/deployments"; ?>

        <a
          href="<?php echo $link ?>">

          <?= isset($exploded[1]) ? $exploded[1] : $exploded[0]; ?> #<?= $deplyment->id(); ?>
        </a>
      </td>
      <td>

        <a
          href="/P<?= $deplyment->projectId ?>/fortify/<?= $b->buildId ?>/<?= $b->id; ?>">
           #<?= $b->id; ?>
        </a>

        <a class="btn btn-small" style="padding:1px 5px"
          href="/P<?= $deplyment->projectId ?>/fortify/<?= $b->buildId ?>">
          New Build
        </a>
      </td>
      <td><?= substr($b->branch,0,20 ) ?></td>
      <td><?= implode(', ', $hostnames) ?></td>
      <td><?= $deplyment->passed ? 'Passed' : ($deplyment->pending ? 'Pending' : 'Failed'); ?></td>
      <td><?= ucfirst($user->username) ?></td>
      <td><?= ucfirst($deplyment->updatedAt) ?></td>
    </tr>
  <?php } ?>
</table>
