<?php
/**
 * Author: oke.ugwu
 * Date: 28/08/13 18:25
 * @var $this \Sidekick\Applications\Diffuse\Views\DeploymentsView
 */
?>
<h2>Deployments <?= $this->getProject() ? 'For ' . $this->getProject()->name : ''; ?></h2>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>

<table class="table">
  <tr>
    <th>Project</th>
    <th>Build Number</th>
    <th>Branch</th>
    <th>Hosts</th>
    <th>Status</th>
    <th>User</th>
  </tr>
  <?php
  /***
   * @var $deplyment \Sidekick\Components\Diffuse\Mappers\Deployment
   */

  foreach($this->getDeploymentlist() as $deplyment)
  {
    $project = new \Sidekick\Components\Projects\Mappers\Project($deplyment->project_id);
    $b = new \Sidekick\Components\Fortify\Mappers\BuildRun($deplyment->version_id);
    $user = new \Sidekick\Components\Users\Mappers\User($deplyment->user_id);
    $hosts = json_decode($deplyment->hosts);
    $hostnames = [];

    if($hosts)
    {
      foreach($hosts as $h)
      {
        $host = new \Sidekick\Components\Servers\Mappers\Server($h);
        $hostnames[] = $host->name;
      }
    }


    ?>
    <tr class="<?= $this->textClass($deplyment->passed);  ?>">
      <td>
        <?php $exploded = explode(":", $project->name); ?>
        <span class="label label-default"><?= isset($exploded[1]) ? $exploded[0] : ''; ?></span>&nbsp;&nbsp;
        <a
          href="/P<?= $deplyment->project_id ?>/diffuse/deployments">

          <?= isset($exploded[1]) ? $exploded[1] : $exploded[0]; ?>  
        </a>
      </td>
      <td>

        <a
          href="/P<?= $deplyment->project_id ?>/fortify/<?= $b->build_id ?>/<?= $b->id; ?>">
           #<?= $b->id; ?>
        </a>
      </td>
      <td><?= substr($b->branch,0,20 ) ?></td>
      <td><?= implode(', ', $hostnames) ?></td>
      <td><?= ucfirst($b->result) ?></td>
      <td><?= ucfirst($user->username) ?></td>
    </tr>
  <?php } ?>
</table>
