<?php
/**
 * Author: oke.ugwu
 * Date: 28/08/13 18:25
 * @var $this \Sidekick\Applications\Diffuse\Views\DeploymentView
 */
?>
<h2>Deploy Project - <?= $this->project()->name ?></h2>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>
<?= $this->form()->open() ?>
<?= $this->form()->token() ?>
<?= $this->form()->formNameInput() ?>
  <div>
    <?= $this->form()->getElement('buildId'); ?>
    <p>Select Deployment Config: <br/><?= $this->form()->getElement('platformId'); ?></p>

    <p>Deploy Base: <br/><?= $this->form()->getElement('deploy_base') ?></p>
    <p>Choose Servers:</p>
    <?php
    $groups = [];
    foreach($this->hosts() as $host):
      //bit of magic to group them
      $groups[$host->name][] = $host->id;
     endforeach; ?>

    <?php
    foreach($groups as $group => $hosts):

      ?>

      <div class="pull-left" style="  border: 1px solid #ddd;
    margin: 10px;
    padding: 10px;
    min-height: 200px;">
      <h3 class="hostsHead"><?= $group ?> <input class="headCheckBox" id="group-<?php echo $group; ?>" type="checkbox"></h3>
      <?php
      foreach($hosts as $host):
      ?>

       <p class="hostsList pull-left" style=" padding:10px; text-align: center;">
        <?= $this->form()->getElement("deploymentHosts[$host]") ?>
      </p>
      <?php endforeach; ?>
      </div>
    <?php endforeach; ?>

    <script>

      var hostGroups = JSON.parse('<?= json_encode($groups); ?>');
    </script>
    <div class="clearfix"></div>
  </div>
<p>Comment:<br/><?= $this->form()->getElement('comment') ?></p>
<?= $this->form()->getElement('submit') ?>
<?= $this->form()->close() ?>
