<?php
/**
 * Author: oke.ugwu
 * Date: 28/08/13 18:25
 * @var $this \Sidekick\Applications\Diffuse\Views\DeploymentView
 */
?>
<h2>Deploy Project - <?= $this->project()->name ?></h2>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>
<?= $this->form()->open() ?>
<?= $this->form()->token() ?>
<?= $this->form()->formNameInput() ?>
  <div>
    <?= $this->form()->getElement('buildId'); ?>

    <?php
    $hasConfigAssigned = $this->form()->getElement('configId')->type() == 'hidden';
    if(!$hasConfigAssigned): ?>
    <p>Select Deployment Config: <br/><?php endif; ?>
      <?= $this->form()->getElement('configId'); ?>

      <a href="#" id="stepsToggle" class="pull-right" >
        Show Steps<i class="icon-arrow-right"></i> </a>
    <div class="clearfix"></div>
    <div id="steps" class="well pull-right" style="display:none;">
      <?php
       foreach($this->getSteps() as $platformId => $steps)
       { ?>
         <ol style="<?= $hasConfigAssigned ? '' : 'display:none' ?>" id="steps-<?= $platformId; ?>">
         <?php
         foreach($steps as $step)
         {
           echo "<li>" . $step->command . '</li>';
         }?>
        </ol>
        <?php
       }
      ?>

    </div>
    </p>

    <p>Deploy Base: <span class="text-error">Only change this if you know what you are doing!</span><br/><?= $this->form()->getElement('deploy_base') ?></p>
    <p>Choose Servers:</p>
    <?php
    $groups = [];
    foreach($this->hosts() as $host):
      //bit of magic to group them
      $groups[$host->name][] = $host->id;
     endforeach; ?>

    <?php
    foreach($groups as $group => $hosts):

      ?>
      <style>
        .activeDeployHost{
          background: #EDFFE0;
        }
        .hostsContainer{
         border: 1px solid #ddd;
         margin: 10px;
         padding: 10px;
        }
        label
        {
          display:inline-block; margin-right:10px;
        }
      </style>
      <div class="pull-left hostsContainer" style="  ">
      <h3 class="hostsHead"><?= $group ?> <input class="headCheckBox" id="group-<?php echo $group; ?>" type="checkbox"></h3>
      <?php
      foreach($hosts as $host):
      ?>

       <p class="hostsList pull-left" style=" padding:10px; text-align: center;">
        <?= $this->form()->getElement("deploymentHosts[$host]") ?>
      </p>
      <?php endforeach; ?>
      </div>
    <?php endforeach; ?>

    <script>

      var hostGroups = JSON.parse('<?= json_encode($groups); ?>');
    </script>
    <div class="clearfix"></div>
  </div>
<div class="">
  <h3>Changes:</h3>
  <table class="table table-striped table-bordered">
  <?php foreach($this->getDeploymentChanges() as $change){
    ?>
    <tr>
      <td><?= $change->subject; ?> </td>
      <td><?= $change->author; ?> </td>
      <td><?= date('y-m-d H:i', strtotime($change->committed_at)); ?> </td>
      <td> <?= substr($change->commit_hash, 0,8); ?></td>
    </tr>
    <?php
  }  ?>
  </table>
</div>
<p>Comment:<br/><?= $this->form()->getElement('comment') ?></p>


<?= $this->form()->getElement('submit') ?>
<?= $this->form()->close() ?>
