<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 17/07/13
 * Time: 17:19
 * To change this template use File | Settings | File Templates.
 */
?>
<h1>Code Distributions</h1>
<p><strong>The following versions are pending, and have not been deployed
           anywhere:</strong></p>
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
  <tr>
    <th>Project</th>
    <th>Version</th>
    <th>Type</th>
    <th>State</th>
    <th>Updated</th>
  </tr>
  </thead>
  <tbody>
  <?php
    $versions=$this->getAttentionVersions();
    foreach($versions as $version)
    {
      echo "<tr>";
      echo "<td>" . $version->projectid . "</td>";
      echo "<td><a href='/diffuse/" . $version->projectid . "/" . $version->id . "'>" . $version->major . "." . $version->minor . "." . $version->revision . "</a></td>";
      echo "<td>" . $version->type . "</td>";
      echo "<td>" . $version->version_state . "</td>";
      echo "<td>" . date("d/M/Y", strtotime($version->updated_at)) . "</td>";
      echo "</tr>";
  }
  ?>
  </tbody>
</table>

