<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 17/07/13
 * Time: 17:19
 * To change this template use File | Settings | File Templates.
 */
?>
<h1>Code Distributions</h1>
<form class="form-inline well">
  <label for="stateSelect">Show versions that are:</label>
  <select id="stateSelect" name="stateSelect">
    <?php foreach($this->getStates() as $sKey => $sValue): ?>
      <option value="<?= $sValue ?>"><?= $sValue ?></option>
    <?php endforeach; ?>
  </select>
  <label class="checkbox"><input type="checkbox" id="allPlatforms"
                                 name="allPlatforms"/> On all platforms</label>
  <button type="submit" id="updateButton" class="btn btn-primary">Update
  </button>
</form>
<p><strong>The following versions match your criteria:</strong></p>
<table class="table table-striped table-bordered table-hover table-condensed"
       id="versionTable">
  <thead>
  <tr>
    <th>Project</th>
    <th>Version</th>
    <th>Type</th>
    <th>State(s)</th>
    <th>Updated</th>
  </tr>
  </thead>
  <tbody>
  <?php foreach($this->getMatchingVersions() as $version): ?>
    <tr>
      <td><?= $version->project ?></td>
      <td>
        <a href="<?= $this->appBaseUri() . "/v/" . $version->versionid ?>">
          <?= $version->version ?>
        </a>
      </td>
      <td><?= $version->type ?></td>
      <td>
        <?php foreach($version->states as $platform => $state): ?>
          <?= "$platform: $state<br />"; ?>
        <?php endforeach; ?>
      </td>
      <td><?= $version->updated ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<div id="modal" class="modal hide">
  <div class="modal-header">
    <h3>Loading...</h3>
  </div>
  <div class="modal-body">
    <div class="progress progress-striped active">
      <div class="bar" style="width:100%;"></div>
    </div>
  </div>
</div>
