<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 26/07/13
 * Time: 10:08
 * @var $this \Sidekick\Applications\Diffuse\Views\ManageDeploymentStepsView
 */
?>
<h2><?= (!$this->step()->exists()) ? "Add" : "Edit" ?> Deployment Step</h2>
<?php $form = $this->form(); ?>
<?= $form->open(); ?>
<?= $form->formNameInput(); ?>
<?= $form->token(); ?>
<?= $form->getElement("id"); ?>
<?php if($this->step()->exists()): ?>
<h3>Platform: <?= \Cubex\Helpers\Strings::titleize(
    $this->step()->config()->name
  ); ?></h3>
<?php endif; ?>
<?= $form->getElement("platformId"); ?>
<?= $form->getElement("name"); ?>
<?= $form->getElement("command"); ?>
<!-- <div id="configurationTable"></div> -->
<?= $form->getElement("submit"); ?>
<?= $form->close(); ?>
