<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 29/07/13
 * Time: 11:30
 * To change this template use File | Settings | File Templates.
 */
?>
<h1>Manage Platform Hosts</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type ?> ">
    <?= Session::getFlash('msg')->text ?>
  </div>
<?php endif; ?>
<p class="pull-right"><a class="btn btn-info" href="/diffuse/platformhost/<?= $this->_projectId ?>/add">Add Platform Host</a></p>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Platform</th>
      <th>Host</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($this->getHostPlatforms() as $ph): ?>
    <tr>
      <td><?= $this->getPlatformName($ph->platform_id) ?></td>
      <td><?= $this->getHostName($ph->host_id) ?></td>
      <td>
        <a href="/diffuse/platformhost/<?= $ph->project_id . "/" . $ph->platform_id ?>/edit"><i class="icon icon-edit"></i></a>
        <a href="/diffuse/platformhost/<?= $ph->project_id . "/" . $ph->platform_id ?>/delete"><i class="icon icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
