<?php
/**
 * @author: oke.ugwu
 *        Application: Projects
 * @var $this \Sidekick\Applications\Diffuse\Views\PlatformIndex
 */
?>
<h1>Deployment Platforms</h1>
<a href="<?= $this->baseUri() . '/create'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create Platform</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Name</th>
    <th>Description</th>
    <th>Transport Type</th>
    <th>Configuration</th>
    <th>Required Build</th>
    <th>Require Approval</th>
    <th>Last Update</th>
    <th></th>
  </tr>
  <?php foreach($this->getPlatforms() as $platform): ?>
    <tr>
      <td>
        <a href=""><?= $platform->name; ?></a>
      </td>
      <td><?= $platform->description; ?></td>
      <td><?= $platform->transportType; ?></td>
      <td><?= $platform->configuration; ?></td>
      <td>
        <?php if(is_array($platform->requiredBuilds)): ?>
          <?=
          implode(
            '<br/>',
            $this->getRequiredBuilds($platform->requiredBuilds)
          ); ?>
        <?php endif; ?>
      </td>
      <td><?= ($platform->requireApproval) ? 'Yes' : 'No'; ?></td>
      <td><?= date('d/M/Y', strtotime($platform->updated_at)); ?></td>
      <td>
        <a href="<?= $this->baseUri() . '/edit/' . $platform->id(); ?>"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="<?= $this->baseUri() . '/delete/' . $platform->id(); ?>"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
