<?php
/**
 * Author: oke.ugwu
 * Date: 02/07/13 13:22
 *
 * @var $this \Sidekick\Applications\Diffuse\Views\VersionDetails
 */
?>
<h1>Version Details</h1>
<?= $this->getNav()->render(); ?>
<?php if(Session::getFlash('msg')): ?>
<div class="alert alert-<?= Session::getFlash('msg')->type ?> ">
  <?= Session::getFlash('msg')->text ?>
</div>
<?php endif; ?>
<div class="well row-fluid">
  <div class="span6">
    <p>Major: <?= $version->major ?></p>

    <p>Minor: <?= $version->minor ?></p>

    <p>Build: <?= $version->build ?></p>

    <p>Revision: <?= $version->revision ?></p>

    <p>Type: <?= $version->type ?></p>
  </div>
  <div class="span6">
    <p>Commit Range:
      <?= substr($version->fromCommitHash, 0, 8) ?> -
      <?= substr($version->toCommitHash, 0, 8) ?>
    </p>

    <p>Last Updated: <?=
      date(
        'd M Y',
        strtotime($version->updatedAt)
      ) ?></p>

    <div>
      <strong>Members</strong>
      <ul>
        <?php foreach($this->getUsers() as $u): ?>
          <li><?= $u->user()->displayName; ?></li>
        <?php endforeach; ?>
      </ul>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
<h2>Status</h2>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Platform</th>
    <th>State</th>
  </tr>
  </thead>
  <tbody>
  <?php foreach($this->getPlatforms() as $platform): ?>
    <tr>
      <td><?= $platform->name ?></td>
      <td><?= $this->getStateOnPlatform($platform->id); ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
