<?php
/**
 * Author: oke.ugwu
 * Date: 02/07/13 12:13
 *
 * @var $this \Sidekick\Applications\Diffuse\Views\VersionsList
 */
?>
<!--might be better to pass basePath instead of project id-->
<h1>Versions</h1>

<ul class="nav nav-pills">
  <li><a href="/diffuse/approval/<?= $this->_projectId ?>">
      Approval Configuration
    </a></li>
  <li><a href="/diffuse/platformhost/<?= $this->_projectId ?>">
      Manage Platform Hosts
    </a></li>
  <li><a href="/diffuse/stages/<?= $this->_projectId ?>">
      Manage Deployment Process
    </a></li>
</ul>

<div class="clearfix"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<div class="well">
  <strong>Create New Version:</strong>
  <?php
  echo $this->createVersionForm()->token();
  echo $this->createVersionForm()->formNameInput();
  ?>
  <?= $this->createVersionForm()->getElement('projectId') ?>
  <?= $this->createVersionForm()->getElement('type') ?>
  <?= $this->createVersionForm()->getElement('versionNumberType') ?>
  <?= $this->createVersionForm()->getElement('submit'); ?>
  <?= $this->createVersionForm()->close() ?>
</div>

<table class="table table-striped table-bordered table-condensed">
  <tr class="info">
    <th class="">Version</th>
    <th>Status</th>
    <th>Commit Range</th>
    <th>Created</th>
    <th>Last Updated</th>
  </tr>
  <?php foreach($this->getVersions() as $v): ?>
    <tr class="">
    <td>
      <a href="/diffuse/<?= $this->_projectId . "/" . $v->id() ?>">
        <?= $v->major . '.' . $v->minor . '.' . $v->build . '.' . $v->revision ?>
      </a>
    </td>
    <?php
    $states = $this->getStates($v->id());
    if($states->count() == 0):
      ?>
      <td colspan="4">Not reviewed on any platform
    <?php else: ?>
      <td>
        <?php foreach($states as $state): ?>
          <?= $this->getPlatformName($state->platformId) ?>:
          <span class="text-<?=
          $this->stateClass(
            $state->state
          ) ?>"><?= $state->state ?></span><br/>
        <?php endforeach; ?>
      </td>
      <td>
        <?= substr($v->fromCommitHash, 0, 8); ?> - <?=
        substr(
          $v->toCommitHash,
          0,
          8
        ); ?>
      </td>
      <td><?= date('d M y', strtotime($v->createdAt)); ?></td>
      <td><?= date('d M y H:i:s', strtotime($v->updatedAt)); ?></td>
      </tr>
    <?php
    endif;
  endforeach;
  ?>
</table>
