<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Sam.Waters
 * Date: 23/07/13
 * Time: 11:09
 * To change this template use File | Settings | File Templates.
 */
?>
<h1>Platform: <?php echo $this->_platform->name; ?></h1>
<?= $this->getNav()->render(); ?>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash("msg")->type ?>">
    <?= Session::getFlash('msg')->text ?>
  </div>
<?php endif; ?>
<?php if($this->_state == \Sidekick\Components\Diffuse\Enums\VersionState::REJECTED): ?>
  <div class="alert alert-error">This version has been rejected</div>
<?php endif; ?>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Approval Required From</th>
    <th>Consistency Level</th>
    <th>Required</th>
    <th>Approval Received</th>
  </tr>
  </thead>
  <tbody>
  <?php foreach($this->getApprovalConfiguration() as $approval): ?>
    <tr>
      <td><?= $approval->role ?></td>
      <td><?= $approval->consistency_level ?></td>
      <td><?= ($approval->required) ? "Yes" : "No" ?></td>
      <td><?=
        ($this->isApproved(
          $approval->role,
          $approval->consistency_level
        )) ? "Yes" : "No" ?>
        (<?= $this->getApproverCount($this->_versionID, $approval->role); ?> /
        <?=
        $this->approversRequired(
          $this->_projectID,
          $approval->role,
          $approval->consistency_level
        ); ?>)
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<div class="row-fluid">
  <div class="span6">
    <h2>Actions</h2>
    <?= $this->getActionForm()->render() ?>
  </div>
  <div class="span6">
    <h2>Deploy</h2>
    <?= $this->getDeployForm()->render() ?>
    <p>Current Status on this platform: <span
        class="text-<?= $this->stateClass($this->_state) ?>"><?= $this->_state ?></span></p>

    <p>
      <a
        href="/diffuse/platform/<?= $this->_projectID . "/" . $this->_versionID . "/" . $this->_platformID; ?>/refresh">Refresh
                                                                                                                        Deploy
                                                                                                                        Status</a>
    </p>
  </div>
  <div class="clearfix"></div>
</div>
<h2>Action History</h2>
<?php foreach($this->getActionHistory() as $action): ?>
  <div class="comment">
    <strong><?= $action->user()->displayName ?></strong>
    (<?= $action->user_role ?>)
    <small><?= date("d M Y H:i", strtotime($action->updatedAt)) ?></small>
    <span class="label label-info"><?= $action->actionType ?></span>

    <p><?= $action->comment ?></p>
  </div>
<?php endforeach; ?>
