<?php
/**
 * @author: oke.ugwu
 * @var $this Sidekick\Applications\Fortify\Views\BuildRunDetails
 */
?>
<h1>Build Log</h1>
<code class="console" style="min-height: 800px;">
  <?php foreach($this->getCommandsRun() as $commandRun): ?>
    <p class="command-title <?= (!$commandRun->passed) ? 'error-text' : '' ?>">
      [<?= date('H:i:s', $commandRun->startTime); ?>]
      <a href="#" id="<?= md5($commandRun->command->command) ?>-trigger"
         onclick="toggle('#<?= md5($commandRun->command->command); ?>');">
        <?= ($commandRun->passed) ? '+' : '-' ?></a>
      <?= $commandRun->command->name ?></p>

    <div id="<?= md5($commandRun->command->command) ?>"
         class="cmdOutput <?= ($commandRun->passed) ? 'hide' : '' ?>">
      <p
        class="command <?= (!$commandRun->passed) ? 'error-text' : '' ?>">
        [<?= date('H:i:s', $commandRun->startTime); ?>]
        &nbsp;&nbsp;<?= $commandRun->command->command; ?> <?= $commandRun->args ?>
      </p>

      <?php foreach($commandRun->commandOutput as $key => $lineValue): ?>
        <?php
        $keyParts   = explode(':', $key);
        $outputLine = false; //start_time or some other "non output" key
        if($keyParts[0] == 'output')
        {
          $outputLine = true;
          $lineTime   = date('H:i:s', $keyParts[1]);
          $lines      = explode("\n", $lineValue);
        }

        $errorLine = false;
        if(isset($keyParts[2]) && $keyParts[2] == 'err')
        {
          $errorLine = true;
        }
        ?>
        <?php if($outputLine): ?>
          <?php foreach($lines as $line): ?>
            <?php if($line == '')
            {
              continue;
            } ?>
            <div class="line <?= (!$commandRun->passed) ? 'error-text' : '' ?>">
              [<?= $lineTime; ?>] &nbsp;&nbsp;<?= $line ?>
            </div>
          <?php endforeach; ?>
        <?php endif; ?>
      <?php endforeach; ?>
    </div>
  <?php endforeach; ?>
</code>

