<?php
/**
 * @author: oke.ugwu
 * @var $this Sidekick\Applications\Fortify\Views\BuildCommands
 */
?>
<h1>Build Commands</h1>
<a href="#myModal"
   class="btn btn-success pull-right"
   style="margin-top:-20px;" role="button" data-toggle="modal">
  <i class="icon-plus icon-white"></i>
  Add Command to Build</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Command</th>
    <th>args</th>
    <th>Name</th>
    <th>Description</th>
    <th>Dependencies</th>
    <th></th>
  </tr>
  <?php if($this->getBuildCommands()): ?>
  <?php foreach($this->getbuildCommands() as $command): ?>
    <tr>
      <td><?= $command->command()->command; ?></td>
      <td><?= implode(',', $command->command()->args); ?></td>
      <td><?= $command->command()->name; ?></td>
      <td><?= $command->command()->description; ?></td>
      <td>
        <?php if(is_array($command->dependencies)): ?>
        <?= implode(',', $command->dependencies); ?>
        <?php endif; ?>
      </td>
      <td>
        <a href="<?= '/fortify/buildCommands/' . $command->commandId.'/'.$command->buildId.'/delete'; ?>"
           title="delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
  <?php endif; ?>
</table>
