<?php
/**
 * Author: oke.ugwu
 * Date: 25/06/13 14:52
 *
 * @var $this \Sidekick\Applications\Fortify\Views\BuildDetailsView
 */
?>
<table class="table table-bordered">
  <tr>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Duration</th>
  </tr>
  <tr>
    <td>
      <?= date('d M Y H:i:s', strtotime($this->run->startTime)) ?>
    </td>
    <td>
      <?= date('d M Y H:i:s', strtotime($this->run->endTime)) ?>
    </td>
    <td>
      <?= $this->getDuration($this->run->endTime, $this->run->startTime) ?>
    </td>
  </tr>
</table>


<h2>Build Commands</h2>
<table class="table table-bordered">
  <tr>
    <th>Exit <br/>Code</th>
    <th>Command</th>
    <th>Start</th>
    <th>Duration</th>
    <th>Actions</th>
    <th>Status</th>
  </tr>
  <?php foreach($this->getCommandsRun() as $command): ?>
    <tr>
      <td><?= $command->exitCode ?></td>
      <td><?= $command->command->command ?></td>
      <td><?= date('H:i:s', $command->startTime) ?></td>
      <td>
        <?php if($command->endTime && $command->startTime): ?>
          <?=
          $this->getDuration(
            date('Y-m-d H:i:s', $command->endTime),
            date('Y-m-d H:i:s', $command->startTime)
          );
          ?>
        <?php endif; ?>
      </td>
      <td>
        <a href="" title="Command Log"><i class="icon-list-alt"></i></a>
        <a
          href="<?= $this->basePath ?>/<?= $command->command->command ?>"
          title="Command Report">
          <i class="icon-file"></i>
        </a>
      </td>
      <td><?= (int)$command->passed ?></td>
    </tr>
  <?php endforeach; ?>
</table>


