<?php
/**
 * @author: oke.ugwu
 * @var $this Sidekick\Applications\Fortify\Views\BuildRunDetails
 */
?>
<?php foreach($this->getCommandsRun() as $commandRun): ?>
  <strong>
    <?= $commandRun->command->command; ?>
    <?= (is_array($commandRun->command->args)) ? implode(
      ' ',
      $commandRun->command->args
    ) : '' ?>
  </strong>
  <?php if($commandRun->passed): ?>
    <div class="well">
      <p class="text-success">Command Passed :)</p>
    </div>
  <?php else: ?>
    <div class="well">
      <strong>Exit Code:</strong><?= $commandRun->exitCode; ?>
      <code class="console">
        <?= implode('<br/>', $commandRun->commandOutput); ?>
      </code>
    </div>
  <?php endif; ?>
<?php endforeach; ?>
