<?php
/**
 * @author: oke.ugwu
 * @var $this Sidekick\Applications\Fortify\Views\BuildRunsList
 */
?>
<table class="table table-striped table-bordered table-condensed">
  <tr class="info">
    <th>Run #</th>
    <th>Branch</th>
    <th>Date</th>
    <th>Hash</th>
    <th>Started</th>
    <th>Duration</th>
    <th>Result</th>
    <th></th>
  </tr>
  <?php if($this->getBuildRuns()): ?>
    <?php foreach($this->getBuildRuns() as $run): ?>
      <tr class="<?= $this->textClass($run->result);  ?>">
        <td><?= $run->id(); ?></td>
        <td><?= $run->branch ?></td>
        <td><?= date('d M y', strtotime($run->createdAt)); ?></td>
        <td><?= substr($run->commitHash, 0, 8); ?></td>
        <td><?= date('d M y H:i:s', strtotime($run->startTime)); ?></td>
        <td title="<?= $run->startTime; ?> - <?= $run->endTime; ?>">
          <?= $this->getDuration($run->endTime, $run->startTime); ?>
        </td>
        <td><?= $run->result; ?></td>
        <td>
          <div class="actions">
          <?php if($run->result == 'pass'): ?>
          <a href="/P<?= $run->projectId ?>/diffuse/<?= $run->id() ?>"><i class="icon-play"></i> Deploy</a>
          <a href="<?= $this->appBaseUri() ?>/<?= $run->buildId ?>/<?= $run->id() ?>/changes"><i class="icon-list"></i> Changes</a>
          <?php endif; ?>
          <?php if($run->result != 'pass'): ?>
          <a href="<?= $this->appBaseUri() ?>/<?= $run->buildId ?>/<?= $run->id() ?>/buildlog"><i class="icon-align-left"></i> View Log</a>

        <?php endif; ?>
          </div>
        </td>
      </tr>
    <?php endforeach; ?>
  <?php endif; ?>
</table>
