<?php
/**
 * Author: oke.ugwu
 * Date: 25/06/13 14:52
 *
 * @var $this \Sidekick\Applications\Fortify\Views\BuildDetailsView
 */
?>
<table class="table table-bordered">
  <tr>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Duration</th>
  </tr>
  <tr>
    <td>
      <?= date('d M Y H:i:s', strtotime($this->run->startTime)) ?>
    </td>
    <td>
      <?= date('d M Y H:i:s', strtotime($this->run->endTime)) ?>
    </td>
    <td>
      <?= $this->getDuration($this->run->endTime, $this->run->startTime) ?>
    </td>
  </tr>
</table>


<h2>Build Commands</h2>
<table class="table table-bordered">
  <tr>
    <th>Exit <br/>Code</th>
    <th>Command</th>
    <th>Start</th>
    <th>Duration</th>
    <th>Actions</th>
    <th>Status</th>
  </tr>
  <?php foreach($this->getCommandsRun() as $command): ?>
    <tr>
      <?php if($command->exitCode !== null): ?>
        <td><a
          href="<?= $this->basePath ?>/buildlog/<?= $command->command->id() ?>"
          title="Command Log"><?= $command->exitCode ?></a></td>
        <td><a
          href="<?= $this->basePath ?>/<?= $command->command->id() ?>"
          title="Command Report"><?= $command->command->name ?></a></td>
        <td><a
          href="<?= $this->basePath ?>/buildlog/<?= $command->command->id() ?>"
          title="Command Log"><?= date('H:i:s', $command->startTime) ?></a></td>
        <td><a
          href="<?= $this->basePath ?>/buildlog/<?= $command->command->id() ?>"
          title="Command Log">
            <?php if($command->endTime && $command->startTime): ?>
              <?=
              $this->getDuration(
                date('Y-m-d H:i:s', $command->endTime),
                date('Y-m-d H:i:s', $command->startTime)
              );
              ?>
            <?php endif; ?></a>
        </td>
        <td>
          <a
          href="<?= $this->basePath ?>/buildlog/<?= $command->command->id() ?>"
          title="Command Log"><i class="icon-list-alt"></i> View Log</a>
          <?php if($command->command->reportNamespace != ''): ?>
          &nbsp;|&nbsp;
          <a
          href="<?= $this->basePath ?>/<?= $command->command->id() ?>"
          title="Command Report">
            <i class="icon-file"></i>View Report
          </a>
          <?php endif; ?>
        </td>
        <td><a
          href="<?= $this->basePath ?>/buildlog/<?= $command->command->id() ?>"
          title="Command Log">
            <i class="icon-<?= $command->passed ? 'ok' : 'remove' ?>"></i></a>
        </td>
      <?php else: ?>
        <td>N/A</td>
        <td><?= $command->command->name ?></td>
        <td colspan="4">This command has not yet been executed</td>
      <?php endif; ?>
    </tr>
  <?php endforeach; ?>
</table>


