<?php
/**
 * Created by JetBrains PhpStorm.
 * User: oke.ugwu
 * Date: 31/05/13
 * Time: 08:44
 * @var $this \Sidekick\Applications\Fortify\Views\BuildChanges.
 */
?>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover table-condensed">
  <tr class="info">
    <th>Hash</th>
    <th>Date</th>
    <th>Subject</th>
    <th>Author</th>
  </tr>
  <?php if($this->getCommits()): ?>
  <?php foreach($this->getCommits() as $c): ?>
    <tr>
      <td>
          <?php echo substr($c->commitHash, 0, 8); ?>
      </td>
      <td>
        <?php echo date('d/M/Y H:i', strtotime($c->committedAt)); ?>
      </td>
      <td><?php echo $c->subject; ?></td>
      <td><?php echo $c->author; ?></td>
    </tr>
  <?php endforeach; ?>
  <?php else: ?>
  <tr>
    <td colspan="4">No changes between current build and previous build</td>
  </tr>
  <?php endif; ?>
</table>
