<?php
/**
 * @author: oke.ugwu
 * @var $this Sidekick\Applications\Fortify\Views\BuildLogView
 */
?>
<?php
$basePath = $this->request()->path(4);
?>
<h1>Build Log</h1>
<div class="btn-group cushion pull-right">
  <a class="btn" href="<?= $basePath ?>/phploc">PHP LOC</a>
  <a class="btn" href="<?= $basePath ?>/phpmd">PHP Mess Detection</a>
  <a class="btn" href="<?= $basePath ?>/phpcs">Style Check Warning</a>
  <a class="btn" href="<?= $basePath ?>/phpunit">PHP Unit</a>
</div>
<div class="clearfix"></div>
<code class="console" style="min-height: 800px;">
  <?php foreach($this->getCommandsRun() as $commandRun): ?>
    <?php
    $txtClass = $this->getTextClass(
      $commandRun->passed,
      $commandRun->exitCode
    );
    ?>
    <p class="command-title <?= $txtClass ?>">
      [<?= date('H:i:s', $commandRun->startTime); ?>]
      <a href="#" id="<?= md5($commandRun->command->command) ?>-trigger"
         class="control"
         onclick="toggle('#<?= md5($commandRun->command->command); ?>');">
        <?= ($commandRun->passed) ? '+' : '-' ?></a>
      <?= $commandRun->command->name ?></p>

    <div id="<?= md5($commandRun->command->command) ?>"
         class="cmdOutput <?= ($commandRun->passed) ? 'hide' : '' ?>">
      <p
        class="command <?= $txtClass ?>">
        [<?= date('H:i:s', $commandRun->startTime); ?>]
        &nbsp;&nbsp;<?= $commandRun->command->command; ?>
        <?= $commandRun->args ?>
      </p>
      <?php foreach($commandRun->commandOutput as $key => $lineValue): ?>
        <?php $outputLine = $this->getOutputLine($key, $lineValue); ?>
        <?php if($outputLine): ?>
          <?php foreach($outputLine->lines as $line): ?>
            <div class="line <?= $txtClass ?>">
              [<?= $outputLine->lineTime; ?>]
              &nbsp;&nbsp;<?= $line ?>
            </div>
          <?php endforeach; ?>
        <?php endif; ?>
      <?php endforeach; ?>
    </div>
  <?php endforeach; ?>
</code>

