<?php
/**
 * Author: oke.ugwu
 * Date: 27/06/13 18:04
 *
 * @var $this \Sidekick\Applications\Fortify\Views\FortifyHome
 */
?>
<h1>Overview (Latest Builds)</h1>
<table class="table">
  <tr>
    <th>Project</th>
    <th>Branch</th>
    <th>Commit Hash</th>
    <th>Build Type</th>
    <th>Started</th>
    <th>Duration</th>
    <th>Status</th>
    <th style="min-width:8em"> </th>
  </tr>
  <?php foreach($this->getBuildRuns() as $b): ?>
    <tr class="<?= $this->textClass($b->result);  ?>">
      <td>
        <?php $exploded = explode(":", $this->project($b->project_id)->name); ?>
        <span class="label label-default"><?= isset($exploded[1]) ? $exploded[0] : ''; ?></span>&nbsp;&nbsp;
        <a
          href="/P<?= $b->project_id ?>/fortify/<?= $b->build_id ?>/<?= $b->id; ?>">

          <?= isset($exploded[1]) ? $exploded[1] : $exploded[0]; ?>: #<?= $b->id; ?>
        </a>
      </td>
      <td  ><?= substr($b->branch,0,20 ) ?></td>
      <td><?= substr($b->commit_hash, 0, 8) ?></td>
      <td><?= $this->build($b->build_id)->name; ?></td>
      <td><?= date('d M Y @ H:i:s', strtotime($b->start_time)) ?></td>
      <td><?= $this->getDuration($b->end_time, $b->start_time) ?></td>
      <td><?= ucfirst($b->result) ?></td>
      <td><a class="btn btn-success" href="/P<?= $b->project_id ?>/fortify">New Build</a></td>
    </tr>
  <?php endforeach; ?>
</table>
