<?php
/**
 * Author: oke.ugwu
 * Date: 27/06/13 18:04
 *
 * @var $this \Sidekick\Applications\Fortify\Views\FortifyHome
 */
?>
<h1>Fortify Home</h1>
<table class="table">
  <tr>
    <th>Project</th>
    <th>Commit Hash</th>
    <th>Build Type</th>
    <th>Started</th>
    <th>Duration</th>
    <th>Status</th>
  </tr>
  <?php foreach($this->getBuildRuns() as $b): ?>
    <tr class="<?= $this->textClass($b->result);  ?>">
      <td>
        <a
          href="/fortify/<?= $b->project_id ?>/<?= $b->build_id ?>/<?= $b->id; ?>">
          <?= $this->project($b->project_id)->name; ?>: Build #<?= $b->id; ?>
        </a>
      </td>
      <td><?= substr($b->commit_hash, 0, 8) ?></td>
      <td><?= $this->build($b->build_id)->name; ?></td>
      <td><?= date('d M Y @ H:i:s', strtotime($b->start_time)) ?></td>
      <td><?= $this->getDuration($b->end_time, $b->start_time) ?></td>
      <td><?= ucfirst($b->result) ?></td>
    </tr>
  <?php endforeach; ?>
</table>
