<?php
/**
 * Author: oke.ugwu
 * Date: 20/06/13 14:54
 *
 * @var $this \Sidekick\Applications\Fortify\Views\PhpCsReport
 */
?>

<h1>PHP Style Check Report</h1>
<p>We are not digging your style! :p</p>
<?php if($this->reportFileFound): ?>
<h2>Summary</h2>
<table class="table table-bordered" style="font-size:11px;">
  <tr>
    <th>Standard</th>
    <th>Total</th>
  </tr>
  <?php foreach($this->getCodeStandardErrorSummary() as $name => $count): ?>
    <tr>
      <td><a href=""><?= $name ?></a></td>
      <td><?= $count ?></td>
    </tr>
  <?php endforeach; ?>
</table>

<h2>Errors (<?= $this->getErrorFilesCount() ?>)</h2>
<?php foreach($this->getErrorFiles() as $file): ?>
  <div class="well">
    <h4><?= $file->fileName ?></h4><br/>
    <table class="table table-bordered" style="font-size:11px;">
      <tr>
        <th>Line</th>
        <th>Error</th>
        <th>Standard</th>
        <th>Category</th>
        <th>Type</th>
      </tr>
      <?php foreach($file->errors as $error): ?>
        <tr>
          <td><?= $error->line ?>,<?= $error->column ?></td>
          <td><?= $error->message ?></td>
          <td><?= $error->standard ?></td>
          <td><?= $error->category ?></td>
          <td><?= $error->type ?></td>
        </tr>
      <?php endforeach; ?>
    </table>
  </div>
<?php endforeach; ?>
<?php else: ?>
<h2>Fortify could not find PHP CS report file</h2>
<?php endif; ?>
