<?php
/**
 * Author: oke.ugwu
 * Date: 20/06/13 14:38
 *
 * @var $this \Sidekick\Applications\Fortify\Views\PhpLocReport
 */
?>
<h1>PHP LOC Report</h1>
<?php if($this->reportFileFound): ?>
  <table class="table table-bordered table-hover">
    <?php foreach($this->getStats() as $k => $v): ?>
      <tr>
        <td><?= $k ?></td>
        <td><?= $v ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php else: ?>
  <h2>Fortify could not find PHP LOC report file</h2>
<?php endif; ?>

