<?php
/**
 * Author: oke.ugwu
 * Date: 20/06/13 18:07
 *
 * @var $this \Sidekick\Applications\Fortify\Views\PhpUnitReport
 */
?>
<h1>PHP Unit Report</h1>
<p>Testing Testing...</p>
<?php if($this->reportFileFound): ?>
  <?php $summary = $this->getTestSummary(); ?>
  <h2>Summary: <?= $summary->name ?></h2>
  <div class="well">
    <p><strong>Assertions: </strong><?= $summary->assertions ?></p>

    <p><strong>Failures: </strong><?= $summary->failures ?></p>

    <p><strong>Errors: </strong><?= $summary->errors ?></p>

    <p><strong>Time: </strong><?= $summary->time ?></p>
  </div>
  <?php foreach($this->getTestData() as $testsuite): ?>
    <a class="testsuite"
       onclick="$('#<?= md5($testsuite['name']) ?>').toggle()">
      <div class="pull-left"><h4><?= $testsuite['name'] ?></h4></div>
      <div class="pull-right">
        <?php
        $class = ($testsuite['errors'] == 0) ?
          "test-passed" : "test-failed";
        ?>
        <div class="<?= $class ?>"></div>
      </div>
      <div class="clearfix"></div>
    </a>
    <div class="hide" id="<?= md5($testsuite['name']) ?>">
      <table class='table table-compacted table-bordered'
             style='font-size:11px;'>
        <tr>
          <th>Name</th>
          <th>Class</th>
          <th>File</th>
          <th>Line</th>
          <th>Assertions</th>
          <th>Time</th>
        </tr>
        <?php foreach($testsuite['testCase'] as $testcase): ?>
          <tr>
            <td><?= $testcase['name'] ?></td>
            <td><?= $testcase['class'] ?></td>
            <td><?= basename($testcase['file']) ?></td>
            <td><?= $testcase['line'] ?></td>
            <td><?= $testcase['assertions'] ?></td>
            <td><?= $testcase['time'] ?></td>
          </tr>
        <?php endforeach; ?>
      </table>
      <?php foreach($testsuite['testSuite'] as $subTestsuites): ?>
        <strong><?= $subTestsuites['name']; ?></strong><br/>
        <table class='table table-compacted table-bordered'
               style='font-size:11px;'>
          <tr>
            <th>Name</th>
            <th>Class</th>
            <th>File</th>
            <th>Line</th>
            <th>Assertions</th>
            <th>Time</th>
          </tr>
          <?php foreach($subTestsuites['testCase'] as $testcase): ?>
            <tr>
              <td><?= $testcase['name'] ?></td>
              <td><?= $testcase['class'] ?></td>
              <td><?= basename($testcase['file']) ?></td>
              <td><?= $testcase['line'] ?></td>
              <td><?= $testcase['assertions'] ?></td>
              <td><?= $testcase['time'] ?></td>
            </tr>
          <?php endforeach; ?>
        </table>
      <?php endforeach; ?>
    </div>
  <?php endforeach; ?>
<?php else: ?>
  <h2>Fortify could not find PHP Unit report file</h2>
<?php endif; ?>
