<?php
/**
 * Description
 *
 * @author Sam Waters <sam.waters@justdevelop.it>
 */
?>
<h1><?= $this->getTitle(); ?> Event Types</h1>
<?php $form = $this->getForm(); ?>
<?= $form->open(); ?>
<?= $form->get("id"); ?>
<div class="row">
  <div class="span4">
    <?= $form->get("eventKey"); ?>
    <?= $form->get("eventDescription"); ?>
    <?= $form->get("eventType"); ?>
  </div>
  <div class="span4">
    <?= $form->get("eventApplications[]"); ?>
  </div>
</div>
<input type="button" class="btn btn-success pull-right dynamic-table-button" value="Add Required Parameter" data-dynamic="event-add-edit" />
<h3>Required Parameters</h3>
<table class="table table-condensed table-bordered table-striped dynamic-table" id="event-add-edit">
  <thead>
    <tr>
      <th>Parameter</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->getRequiredParameters() as $param): ?>
      <tr>
        <td>
          <input type="hidden" name="parameter[]" value="<?= $param ?>" />
          <?= $param ?>
        </td>
        <td><a href="#" class="dynamic-row-delete"><i class="icon-trash"></i></a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>
<input type="submit" class="btn btn-primary" value="<?= $this->getTitle(); ?> Event Type" />
<?= $form->close(); ?>
