<?php
/**
 * Description
 *
 * @author Sam Waters <sam.waters@justdevelop.it>
 */
?>
<h1>Event Types Manager</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<a href="/notify/events/add" class="btn btn-primary pull-right">Add Event Type</a>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Key</th>
      <th>Description</th>
      <th>Application(s)</th>
      <th>Type</th>
      <th>Parameters</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($this->getEventTypes() as $event): ?>
  <tr>
    <td><?= $event->eventKey ?></td>
    <td><?= $event->eventDescription ?></td>
    <td>
      <?php if($event->eventApplications != null): ?>
      <ul>
        <?php foreach($event->eventApplications as $app): ?>
          <li><?= $app ?></li>
        <?php endforeach; ?>
      </ul>
      <?php endif; ?>
    </td>
    <td><?= $event->eventType ?></td>
    <td>
      <?php if($event->eventParams != null): ?>
      <ul>
        <?php foreach($event->eventParams as $param): ?>
          <li><?= $param ?></li>
        <?php endforeach; ?>
      </ul>
      <?php endif; ?>
    </td>
    <td>
      <a href="/notify/events/<?= $event->id ?>/edit"><i class="icon-edit"></i></a>
      <a href="/notify/events/<?= $event->id ?>/delete"><i class="icon-trash"></i></a>
    </td>
  </tr>
  <?php endforeach; ?>
  </tbody>
</table>
