<?php
/**
 * Description
 *
 * @author Sam Waters <sam.waters@justdevelop.it>
 */
?>
<h1>Notification Groups</h1>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<a href="/notify/groups/add" class="btn btn-primary pull-right">Create Group</a>
<table class="table table-condensed table-bordered table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Users</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <?php foreach($this->getGroups() as $group): ?>
      <tr>
        <td><?= $group->groupName ?></td>
        <td>
          <?php if($group->groupUsers != null): ?>
            <ul>
              <?php foreach($group->groupUsers as $user): ?>
                <li><?= $this->getUserFromId($user) ?></li>
              <?php endforeach; ?>
            </ul>
          <?php endif; ?>
        </td>
        <td>
          <a href="/notify/groups/<?= $group->id ?>/edit"><i class="icon-edit"></i></a>
          <a href="/notify/groups/<?= $group->id ?>/delete"><i class="icon-trash"></i></a>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
