<?php
/**
 * Description
 *
 * @author Sam Waters <sam.waters@justdevelop.it>
 */
?>
<h1><?= $this->getTitle() ?> Notification Request</h1>
<?php $form=$this->getForm() ?>
<?= $form->open() ?>
<?= $form->get("id") ?>
<div class="row">
  <div class="span4">
    <?= $form->get("eventKey") ?>
    <?= $form->get("notificationTypes[]") ?>
  </div>
  <div class="span4">
    <?= $form->get("users[]") ?>
    <hr />
    <?= $form->get("groups[]") ?>
  </div>
</div>
<input type="submit" class="btn btn-primary" value="<?= $this->getTitle() ?> Notification Request" />
<?= $form->close() ?>


