<?php
/**
 * Author: oke.ugwu
 * Date: 26/11/13 14:51
 *
 * @var \Sidekick\Applications\Notify\Views\NotifySubscribe $this
 */
?>
<?php
$configItem = $this->getNotifyConfigItem();
?>
<h1>Subscribe to <?= $this->getApp()->name() ?> (<?= $this->getEventName() ?>)
    Events</h1>
<?php if($this->getFlashMessage()): ?>
  <div class="alert alert-<?= $this->getFlashMessage()->type; ?>">
    <?= $this->getFlashMessage()->message; ?>
  </div>
<?php endif; ?>
<form action="<?= $this->baseUri() ?>/<?=
$this->getApp()->name() ?>/<?= $this->getEventKey() ?>" method="post">
  <label for=""><strong>Contact Me By:</strong></label>
  <select name="contactMethod" id="contactMethod" class="input-medium">
    <option value="">--SELECT--</option>
    <?php foreach($this->getContactOptions() as $option => $value): ?>
      <option value="<?= $value ?>" <?=
      ($this->getContactMethod(
        ) === $value) ? 'selected="selected"' : '' ?>><?= $option ?></option>
    <?php endforeach; ?>
  </select>
</form>
<?= $this->form()->open(); ?>
<?= $this->form()->getElement('app') ?>
<?= $this->form()->getElement('eventKey') ?>
<?= $this->form()->getElement('contactMethod') ?>
<label><strong>For:</strong></label>
<table class="table table-bordered">
  <tr>
    <?php foreach($configItem->getFilters() as $filterName => $options): ?>
      <th><?= $filterName ?></th>
    <?php endforeach; ?>
    <th></th>
  </tr>
  <tr>
    <?php foreach($configItem->getFilters() as $filterName => $options): ?>
      <td>
        <?php $name = "filters[$filterName]"; ?>
        <?= $this->form()->getElement($name) ?>
      </td>
    <?php endforeach; ?>
    <td width="120"><?= $this->form()->getElement('subscribe') ?></td>
  </tr>
</table>
<?= $this->form()->close() ?>

<h2>My Subscriptions</h2>
<table class="table table-bordered table-striped">
  <tr>
    <th>Event</th>
    <th>Contact Method</th>
    <th>Filters</th>
    <th width="120"></th>
  </tr>
  <?php foreach($this->getSubscriptions() as $s): ?>
    <tr>
      <td><?= $s->eventKey; ?></td>
      <td><?= last(explode('\\', $s->contactMethod)) ?></td>
      <td>
        <?php $filters = $s->filters ?>
        <?php foreach($filters as $filter): ?>
          <li><?= $filter->name ?> =
            <?= $this->getFilterOptions($filter) ?>
          </li>
        <?php endforeach; ?>
      </td>
      <td width="120">
        <a href="<?= $this->appBaseUri(); ?>/<?=
        $s->id() ?>/unsubscribe"
           class="btn btn-danger btn-block">
          <i class="icon-minus icon-white"></i>
          UnSubscribe</a>
      </td>
    </tr>
  <?php endforeach; ?>

</table>
