<?php
/**
 * Author: oke.ugwu
 * Date: 26/11/13 12:39
 *
 * @var \Sidekick\Applications\Notify\Views\NotifyIndex $this
 */
?>
<?php $selectedApp = $this->getSelectedApp(); ?>
<?php if($selectedApp === null): ?>
  <h1>Apps that support Notifications</h1>
  <table class="table table-bordered">
    <tr>
      <th>App</th>
    </tr>
    <?php foreach($this->getApps() as $key => $app): ?>
      <tr>
        <td>
          <a href="<?= $this->appBaseUri() ?>/<?= $key ?>">
            <?= $app->name() ?></a>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php else: ?>
  <h1><?= $selectedApp->name() ?> Events</h1>
  <?php $config = $selectedApp->getNotifyConfig(); ?>
  <table class="table table-bordered table-hover">
    <tr>
      <th>Event Name</th>
      <th>Description</th>
    </tr>
    <?php foreach($config->items as $config): ?>
      <tr>
        <td><a href="<?= $this->appBaseUri(); ?>/<?=
          $selectedApp->name() ?>/<?= $config->eventKey ?>">
            <?= $config->eventName ?>
          </a>
        </td>
        <td><?= $config->eventDescription ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
