<?php
/**
 * @author: oke.ugwu
 *        Application: Projects
 * @var $this \Sidekick\Applications\Users\Views\UsersIndex
 */
?>
<h1>Users</h1>
<a href="<?= $this->baseUri() . '/create'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Create User</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Name</th>
    <th>Display Name</th>
    <th></th>
  </tr>
  <?php foreach($this->getUsers() as $user): ?>
    <tr>
      <td>
        <a href="<?= $this->baseUri() . '/edit/' . $user->id(); ?>">
          <?= $user->username; ?>
        </a>
      </td>
      <td><?= $user->displayName; ?></td>
      <td>
        <?php if($this->canEdit()): ?>
        <a href="<?= $this->baseUri() . '/edit/' . $user->id(); ?>"
           title="edit"><i class="icon-edit"></i></a>
        <?php endif; ?>
        <?php if($this->canDelete()): ?>
          <a href="<?= $this->baseUri() . '/delete/' . $user->id(); ?>"
             title="delete"><i class="icon-trash"></i></a>
        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
