<?php
/**
 * @author: brooke.bryan
 * Application: Sidekick
 * @var $this \Sidekick\Applications\Overview\Views\ProjectOverview
 */
?>
<h2>
  <?= $this->getProject()->name; ?>  <img
    src="https://raw2.github.com/badges/shields/master/static/travis/travis_<?php
    switch($this->_commitBuild->status)
    {
      case 'success':
        echo 'passing';
        break;
      case 'failed':
        echo 'failing';
        break;
      case 'running':
        echo 'pending';
        break;
    }
    ?>.png" height="143"/>

</h2>
<div class="row-fluid">

  <div class="span7">

    <h3>Recent Builds</h3>
    <table class="table">
      <tr>
        <th>Commit</th>
        <th>Started</th>
        <th>Finished</th>
        <th>Status</th>
      </tr>
      <?php if (!empty($this->_commitBuilds)): ?>
      <?php foreach($this->_commitBuilds as $build): ?>
        <tr>
          <td><?= substr($build->commit, 0, 9); ?></td>
          <td><?= $build->startedAt; ?></td>
          <td><?= $build->finishedAt ? : 'Still Running'; ?></td>
          <td><?= $build->status; ?></td>
        </tr>
      <?php endforeach; ?>
      <?php endif; ?>
    </table>

  </div>
  <div class="span2">

    <div class="well">
      Super Globals
      <strong class="pull-right">
        <?= $this->_insight->getInsight('PhpSuperGlobals', 'count'); ?>
      </strong>
    </div>

    <div class="well">
      ToDos
      <strong class="pull-right">
        <?= $this->_insight->getInsight('ToDos', 'count'); ?>
      </strong>
    </div>

    <div class="well">
      Failed PHP Lint
      <strong class="pull-right">
        <?= $this->_insight->getInsight('PhpLint', 'failed'); ?>
      </strong>
    </div>

  </div>
  <div class="span3">

    <table style="width:100%;">
      <?php foreach($this->getBuildProcessTable() as $stage => $aliases): ?>
        <tr>
          <th colspan="2" class="text-left">
            <?= \Cubex\Helpers\Strings::titleize($stage); ?>
          </th>
        </tr>
        <?php foreach($aliases as $alias => $status): ?>
          <tr>
            <td><?= $alias; ?></td>
            <td>
              <?php if($status == 'success'): ?>
                <span class="label label-success">Success</span>
              <?php elseif($status == 'failure'): ?>
                <span class="label label-important">Failed</span>
              <?php
              elseif($status == 'pending'): ?>
                <span class="label label-info">Pending</span>
              <?php
              else: ?>
                <span class="label">Unknown</span>
              <?php endif; ?>
            </td>
          </tr>
        <?php endforeach; ?>
        <tr>
          <td colspan="2">&nbsp;</td>
        </tr>
      <?php endforeach; ?>
    </table>
  </div>

</div>
