<?php
/**
 * @var $this Sidekick\Applications\Diffuse\Views\Projects\Versions\VersionDetailsView
 */
?>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?php echo Session::getFlash('msg')->type; ?>">
    <?php echo Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>

<div class="flow-container">
  <div class="flow-content">

    <div class="progress progress-striped active" style="height:4px;">
      <?php foreach($this->getPlatformPercentages() as $perc): ?>
        <div class="bar bar-<?= $perc[0]; ?>"
             style="width: <?= $perc[1]; ?>%;"></div>
      <?php endforeach; ?>
    </div>

    <div class="flow-block success">Initiation</div>
    <?php foreach($this->getPlatforms() as $platform): ?>
      <a href="<?= $this->baseUri() . '/p/' . $platform->id(); ?>">
        <div
        class="flow-block <?=
        $this->getPlatformStateClass(
          $platform->id()
        ); ?>">

          <?= \Cubex\Helpers\Strings::titleize($platform->name); ?>
        </div>
      </a>
    <?php endforeach; ?>

    <div class="clearfix"></div>
  </div>
</div>
<ul class="inline text-center">
  <li>Repo: <a href="/repository/commits/<?=
    $this->getVersion()->repoId; ?>"><?=
      idp($this->getVersion()->repo(), "name","Unknown Repo"); ?></a></li>
  <li>Source Build: <a
    href="/fortify/<?= $this->getVersion()->projectId; ?>/<?=
    $this->getVersion()->fortifyBuild()->buildId; ?>/<?=
    $this->getVersion()->buildId; ?>">#<?= $this->getVersion()->buildId; ?>
    </a></li>
  <li>Commit Range:
    <?= substr($this->getVersion()->fromCommitHash, 0, 6); ?> -
    <?= substr($this->getVersion()->toCommitHash, 0, 6); ?>
  </li>
</ul>

<h4>
  Change Log
  <small class="pull-right"><a href="<?= $this->baseUri(); ?>/changelog">Edit
                                                                         Change
                                                                         Log</a>
  </small>
</h4>
<div class="well">
  <?php $changeLog = $this->getVersion()->changeLog; ?>
  <?php if(!empty($changeLog)): ?>
    <?= nl2br($changeLog); ?>
  <?php else: ?>
    No change log exists for this version.  Please <a
    href="<?= $this->baseUri(); ?>/changelog">make one</a> :)
  <?php endif ?>
</div>

<?php if($this->_commits !== null): ?>
  <?php foreach($this->_commits as $commit): ?>
    <div class="media">
      <a class="pull-left" href="#">
        <img class="media-object"
             src="http://www.gravatar.com/avatar/<?php
             echo md5(strtolower($commit->author)); ?>?s=50">
      </a>

      <div class="media-body action-box">
        <h4 class="media-deading">
          <?= $commit->author; ?>
          <small class="pull-right">
            <a href="#"><?= substr($commit->commitHash, 0, 6); ?></a> -
            <?= date("d M Y H:i", strtotime($commit->committedAt)) ?>
          </small>
        </h4>
        <?php if(empty($commit->message)): ?>
          <p><?= $commit->subject; ?></p>
        <?php else: ?>
          <h3><?= $commit->subject; ?></h3>
          <p><?= $commit->message; ?></p>
        <?php endif ?>
      </div>
    </div>
  <?php endforeach; ?>
<?php else: ?>
  <p class="text-center">No commits have been tracked to this version :s</p>
<?php endif ?>
